/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WidgetsRouteImport } from './routes/widgets'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SupplementsRouteImport } from './routes/supplements'
import { Route as StreakRouteImport } from './routes/streak'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as PregnancyRouteImport } from './routes/pregnancy'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as HomeDraftRouteImport } from './routes/home-draft'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as CalendarRouteImport } from './routes/calendar'
import { Route as BuddyRouteImport } from './routes/buddy'
import { Route as BodyiqRouteImport } from './routes/bodyiq'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as NutritionIndexRouteImport } from './routes/nutrition.index'
import { Route as NotificationsIndexRouteImport } from './routes/notifications.index'
import { Route as MindfulnessIndexRouteImport } from './routes/mindfulness.index'
import { Route as JourneyIndexRouteImport } from './routes/journey.index'
import { Route as HabitsIndexRouteImport } from './routes/habits.index'
import { Route as CycleIndexRouteImport } from './routes/cycle.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as CoachesIndexRouteImport } from './routes/coaches.index'
import { Route as CheckinIndexRouteImport } from './routes/checkin.index'
import { Route as ChallengesIndexRouteImport } from './routes/challenges.index'
import { Route as ArticlesIndexRouteImport } from './routes/articles.index'
import { Route as WorkoutsSummaryRouteImport } from './routes/workouts.summary'
import { Route as WorkoutsProgramsRouteImport } from './routes/workouts.programs'
import { Route as WorkoutsLiveRouteImport } from './routes/workouts.live'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ProfileThemeRouteImport } from './routes/profile.theme'
import { Route as ProfileTermsRouteImport } from './routes/profile.terms'
import { Route as ProfileSubscriptionRouteImport } from './routes/profile.subscription'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfileReferralRouteImport } from './routes/profile.referral'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as ProfilePaymentRouteImport } from './routes/profile.payment'
import { Route as ProfileNotificationsPrefsRouteImport } from './routes/profile.notifications-prefs'
import { Route as ProfileLanguageRouteImport } from './routes/profile.language'
import { Route as ProfileHelpRouteImport } from './routes/profile.help'
import { Route as ProfileFeedbackRouteImport } from './routes/profile.feedback'
import { Route as ProfileExportRouteImport } from './routes/profile.export'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ProfileDevicesRouteImport } from './routes/profile.devices'
import { Route as ProfileDeleteRouteImport } from './routes/profile.delete'
import { Route as ProfileBackupRouteImport } from './routes/profile.backup'
import { Route as ProfileAboutRouteImport } from './routes/profile.about'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingTypesRouteImport } from './routes/onboarding.types'
import { Route as OnboardingTrialRouteImport } from './routes/onboarding.trial'
import { Route as OnboardingStatsRouteImport } from './routes/onboarding.stats'
import { Route as OnboardingPermissionsRouteImport } from './routes/onboarding.permissions'
import { Route as OnboardingNutritionGoalRouteImport } from './routes/onboarding.nutrition-goal'
import { Route as OnboardingLocationPrefRouteImport } from './routes/onboarding.location-pref'
import { Route as OnboardingLevelRouteImport } from './routes/onboarding.level'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding.goal'
import { Route as OnboardingFrequencyRouteImport } from './routes/onboarding.frequency'
import { Route as OnboardingDobRouteImport } from './routes/onboarding.dob'
import { Route as OnboardingDietRouteImport } from './routes/onboarding.diet'
import { Route as OnboardingCycleDataRouteImport } from './routes/onboarding.cycle-data'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as OnboardingAuthRouteImport } from './routes/onboarding.auth'
import { Route as OnboardingActivityRouteImport } from './routes/onboarding.activity'
import { Route as NutritionShoppingRouteImport } from './routes/nutrition.shopping'
import { Route as NutritionRecipesRouteImport } from './routes/nutrition.recipes'
import { Route as NutritionLogRouteImport } from './routes/nutrition.log'
import { Route as NutritionIdRouteImport } from './routes/nutrition.$id'
import { Route as NotificationsSettingsRouteImport } from './routes/notifications.settings'
import { Route as MindfulnessIdRouteImport } from './routes/mindfulness.$id'
import { Route as JourneySymptomsRouteImport } from './routes/journey.symptoms'
import { Route as JourneyMoodRouteImport } from './routes/journey.mood'
import { Route as JourneyMeasurementsRouteImport } from './routes/journey.measurements'
import { Route as JourneyInsightsRouteImport } from './routes/journey.insights'
import { Route as JourneyGoalsRouteImport } from './routes/journey.goals'
import { Route as JourneyCalendarRouteImport } from './routes/journey.calendar'
import { Route as JourneyAwardsRouteImport } from './routes/journey.awards'
import { Route as HabitsNewRouteImport } from './routes/habits.new'
import { Route as CycleLogRouteImport } from './routes/cycle.log'
import { Route as CommunityInviteRouteImport } from './routes/community.invite'
import { Route as CommunityGroupsRouteImport } from './routes/community.groups'
import { Route as CommunityEventsRouteImport } from './routes/community.events'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as CoachesIdRouteImport } from './routes/coaches.$id'
import { Route as CheckinWaterDraftRouteImport } from './routes/checkin.water-draft'
import { Route as CheckinWaterRouteImport } from './routes/checkin.water'
import { Route as CheckinStepsRouteImport } from './routes/checkin.steps'
import { Route as CheckinSleepRouteImport } from './routes/checkin.sleep'
import { Route as ChallengesPhaseRouteImport } from './routes/challenges.phase'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthNewPasswordRouteImport } from './routes/auth.new-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as WorkoutsProgramsIdRouteImport } from './routes/workouts.programs.$id'
import { Route as WorkoutsIdPlayRouteImport } from './routes/workouts.$id.play'
import { Route as CoachesIdChatRouteImport } from './routes/coaches.$id.chat'
import { Route as CoachesIdBookRouteImport } from './routes/coaches.$id.book'

const WidgetsRoute = WidgetsRouteImport.update({
  id: '/widgets',
  path: '/widgets',
  getParentRoute: () => rootRouteImport,
} as any)
const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsRoute = SupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const StreakRoute = StreakRouteImport.update({
  id: '/streak',
  path: '/streak',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const PregnancyRoute = PregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeDraftRoute = HomeDraftRouteImport.update({
  id: '/home-draft',
  path: '/home-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRoute = CalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const BuddyRoute = BuddyRouteImport.update({
  id: '/buddy',
  path: '/buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const BodyiqRoute = BodyiqRouteImport.update({
  id: '/bodyiq',
  path: '/bodyiq',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIndexRoute = NutritionIndexRouteImport.update({
  id: '/nutrition/',
  path: '/nutrition/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsIndexRoute = NotificationsIndexRouteImport.update({
  id: '/notifications/',
  path: '/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const MindfulnessIndexRoute = MindfulnessIndexRouteImport.update({
  id: '/mindfulness/',
  path: '/mindfulness/',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyIndexRoute = JourneyIndexRouteImport.update({
  id: '/journey/',
  path: '/journey/',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsIndexRoute = HabitsIndexRouteImport.update({
  id: '/habits/',
  path: '/habits/',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleIndexRoute = CycleIndexRouteImport.update({
  id: '/cycle/',
  path: '/cycle/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIndexRoute = CoachesIndexRouteImport.update({
  id: '/coaches/',
  path: '/coaches/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinIndexRoute = CheckinIndexRouteImport.update({
  id: '/checkin/',
  path: '/checkin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIndexRoute = ChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIndexRoute = ArticlesIndexRouteImport.update({
  id: '/articles/',
  path: '/articles/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsSummaryRoute = WorkoutsSummaryRouteImport.update({
  id: '/workouts/summary',
  path: '/workouts/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsProgramsRoute = WorkoutsProgramsRouteImport.update({
  id: '/workouts/programs',
  path: '/workouts/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsLiveRoute = WorkoutsLiveRouteImport.update({
  id: '/workouts/live',
  path: '/workouts/live',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/workouts/$id',
  path: '/workouts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileThemeRoute = ProfileThemeRouteImport.update({
  id: '/profile/theme',
  path: '/profile/theme',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileTermsRoute = ProfileTermsRouteImport.update({
  id: '/profile/terms',
  path: '/profile/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSubscriptionRoute = ProfileSubscriptionRouteImport.update({
  id: '/profile/subscription',
  path: '/profile/subscription',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/profile/settings',
  path: '/profile/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileReferralRoute = ProfileReferralRouteImport.update({
  id: '/profile/referral',
  path: '/profile/referral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/profile/privacy',
  path: '/profile/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePaymentRoute = ProfilePaymentRouteImport.update({
  id: '/profile/payment',
  path: '/profile/payment',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileNotificationsPrefsRoute =
  ProfileNotificationsPrefsRouteImport.update({
    id: '/profile/notifications-prefs',
    path: '/profile/notifications-prefs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileLanguageRoute = ProfileLanguageRouteImport.update({
  id: '/profile/language',
  path: '/profile/language',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/profile/help',
  path: '/profile/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileFeedbackRoute = ProfileFeedbackRouteImport.update({
  id: '/profile/feedback',
  path: '/profile/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileExportRoute = ProfileExportRouteImport.update({
  id: '/profile/export',
  path: '/profile/export',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDevicesRoute = ProfileDevicesRouteImport.update({
  id: '/profile/devices',
  path: '/profile/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileDeleteRoute = ProfileDeleteRouteImport.update({
  id: '/profile/delete',
  path: '/profile/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileBackupRoute = ProfileBackupRouteImport.update({
  id: '/profile/backup',
  path: '/profile/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAboutRoute = ProfileAboutRouteImport.update({
  id: '/profile/about',
  path: '/profile/about',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTypesRoute = OnboardingTypesRouteImport.update({
  id: '/onboarding/types',
  path: '/onboarding/types',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTrialRoute = OnboardingTrialRouteImport.update({
  id: '/onboarding/trial',
  path: '/onboarding/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStatsRoute = OnboardingStatsRouteImport.update({
  id: '/onboarding/stats',
  path: '/onboarding/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPermissionsRoute = OnboardingPermissionsRouteImport.update({
  id: '/onboarding/permissions',
  path: '/onboarding/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNutritionGoalRoute = OnboardingNutritionGoalRouteImport.update({
  id: '/onboarding/nutrition-goal',
  path: '/onboarding/nutrition-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLocationPrefRoute = OnboardingLocationPrefRouteImport.update({
  id: '/onboarding/location-pref',
  path: '/onboarding/location-pref',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLevelRoute = OnboardingLevelRouteImport.update({
  id: '/onboarding/level',
  path: '/onboarding/level',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFrequencyRoute = OnboardingFrequencyRouteImport.update({
  id: '/onboarding/frequency',
  path: '/onboarding/frequency',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDobRoute = OnboardingDobRouteImport.update({
  id: '/onboarding/dob',
  path: '/onboarding/dob',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDietRoute = OnboardingDietRouteImport.update({
  id: '/onboarding/diet',
  path: '/onboarding/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCycleDataRoute = OnboardingCycleDataRouteImport.update({
  id: '/onboarding/cycle-data',
  path: '/onboarding/cycle-data',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAuthRoute = OnboardingAuthRouteImport.update({
  id: '/onboarding/auth',
  path: '/onboarding/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingActivityRoute = OnboardingActivityRouteImport.update({
  id: '/onboarding/activity',
  path: '/onboarding/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionShoppingRoute = NutritionShoppingRouteImport.update({
  id: '/nutrition/shopping',
  path: '/nutrition/shopping',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRecipesRoute = NutritionRecipesRouteImport.update({
  id: '/nutrition/recipes',
  path: '/nutrition/recipes',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionLogRoute = NutritionLogRouteImport.update({
  id: '/nutrition/log',
  path: '/nutrition/log',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionIdRoute = NutritionIdRouteImport.update({
  id: '/nutrition/$id',
  path: '/nutrition/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsSettingsRoute = NotificationsSettingsRouteImport.update({
  id: '/notifications/settings',
  path: '/notifications/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const MindfulnessIdRoute = MindfulnessIdRouteImport.update({
  id: '/mindfulness/$id',
  path: '/mindfulness/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneySymptomsRoute = JourneySymptomsRouteImport.update({
  id: '/journey/symptoms',
  path: '/journey/symptoms',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyMoodRoute = JourneyMoodRouteImport.update({
  id: '/journey/mood',
  path: '/journey/mood',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyMeasurementsRoute = JourneyMeasurementsRouteImport.update({
  id: '/journey/measurements',
  path: '/journey/measurements',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyInsightsRoute = JourneyInsightsRouteImport.update({
  id: '/journey/insights',
  path: '/journey/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyGoalsRoute = JourneyGoalsRouteImport.update({
  id: '/journey/goals',
  path: '/journey/goals',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyCalendarRoute = JourneyCalendarRouteImport.update({
  id: '/journey/calendar',
  path: '/journey/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyAwardsRoute = JourneyAwardsRouteImport.update({
  id: '/journey/awards',
  path: '/journey/awards',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsNewRoute = HabitsNewRouteImport.update({
  id: '/habits/new',
  path: '/habits/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleLogRoute = CycleLogRouteImport.update({
  id: '/cycle/log',
  path: '/cycle/log',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityInviteRoute = CommunityInviteRouteImport.update({
  id: '/community/invite',
  path: '/community/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityGroupsRoute = CommunityGroupsRouteImport.update({
  id: '/community/groups',
  path: '/community/groups',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityEventsRoute = CommunityEventsRouteImport.update({
  id: '/community/events',
  path: '/community/events',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/community/$id',
  path: '/community/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesIdRoute = CoachesIdRouteImport.update({
  id: '/coaches/$id',
  path: '/coaches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinWaterDraftRoute = CheckinWaterDraftRouteImport.update({
  id: '/checkin/water-draft',
  path: '/checkin/water-draft',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinWaterRoute = CheckinWaterRouteImport.update({
  id: '/checkin/water',
  path: '/checkin/water',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinStepsRoute = CheckinStepsRouteImport.update({
  id: '/checkin/steps',
  path: '/checkin/steps',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinSleepRoute = CheckinSleepRouteImport.update({
  id: '/checkin/sleep',
  path: '/checkin/sleep',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesPhaseRoute = ChallengesPhaseRouteImport.update({
  id: '/challenges/phase',
  path: '/challenges/phase',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/challenges/$id',
  path: '/challenges/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/auth/new-password',
  path: '/auth/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/articles/$id',
  path: '/articles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsProgramsIdRoute = WorkoutsProgramsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutsProgramsRoute,
} as any)
const WorkoutsIdPlayRoute = WorkoutsIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => WorkoutsIdRoute,
} as any)
const CoachesIdChatRoute = CoachesIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CoachesIdRoute,
} as any)
const CoachesIdBookRoute = CoachesIdBookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => CoachesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/achievements': typeof AchievementsRoute
  '/assistant': typeof AssistantRoute
  '/bodyiq': typeof BodyiqRoute
  '/buddy': typeof BuddyRoute
  '/calendar': typeof CalendarRoute
  '/circle': typeof CircleRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/home-draft': typeof HomeDraftRoute
  '/paywall': typeof PaywallRoute
  '/pregnancy': typeof PregnancyRoute
  '/screens': typeof ScreensRoute
  '/search': typeof SearchRoute
  '/streak': typeof StreakRoute
  '/supplements': typeof SupplementsRoute
  '/system': typeof SystemRoute
  '/timer': typeof TimerRoute
  '/widgets': typeof WidgetsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/phase': typeof ChallengesPhaseRoute
  '/checkin/sleep': typeof CheckinSleepRoute
  '/checkin/steps': typeof CheckinStepsRoute
  '/checkin/water': typeof CheckinWaterRoute
  '/checkin/water-draft': typeof CheckinWaterDraftRoute
  '/coaches/$id': typeof CoachesIdRouteWithChildren
  '/community/$id': typeof CommunityIdRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/invite': typeof CommunityInviteRoute
  '/cycle/log': typeof CycleLogRoute
  '/habits/new': typeof HabitsNewRoute
  '/journey/awards': typeof JourneyAwardsRoute
  '/journey/calendar': typeof JourneyCalendarRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/insights': typeof JourneyInsightsRoute
  '/journey/measurements': typeof JourneyMeasurementsRoute
  '/journey/mood': typeof JourneyMoodRoute
  '/journey/symptoms': typeof JourneySymptomsRoute
  '/mindfulness/$id': typeof MindfulnessIdRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/nutrition/$id': typeof NutritionIdRoute
  '/nutrition/log': typeof NutritionLogRoute
  '/nutrition/recipes': typeof NutritionRecipesRoute
  '/nutrition/shopping': typeof NutritionShoppingRoute
  '/onboarding/activity': typeof OnboardingActivityRoute
  '/onboarding/auth': typeof OnboardingAuthRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/cycle-data': typeof OnboardingCycleDataRoute
  '/onboarding/diet': typeof OnboardingDietRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/frequency': typeof OnboardingFrequencyRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/level': typeof OnboardingLevelRoute
  '/onboarding/location-pref': typeof OnboardingLocationPrefRoute
  '/onboarding/nutrition-goal': typeof OnboardingNutritionGoalRoute
  '/onboarding/permissions': typeof OnboardingPermissionsRoute
  '/onboarding/stats': typeof OnboardingStatsRoute
  '/onboarding/trial': typeof OnboardingTrialRoute
  '/onboarding/types': typeof OnboardingTypesRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/delete': typeof ProfileDeleteRoute
  '/profile/devices': typeof ProfileDevicesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/export': typeof ProfileExportRoute
  '/profile/feedback': typeof ProfileFeedbackRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications-prefs': typeof ProfileNotificationsPrefsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/referral': typeof ProfileReferralRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/subscription': typeof ProfileSubscriptionRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/reports/$id': typeof ReportsIdRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/live': typeof WorkoutsLiveRoute
  '/workouts/programs': typeof WorkoutsProgramsRouteWithChildren
  '/workouts/summary': typeof WorkoutsSummaryRoute
  '/articles/': typeof ArticlesIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/checkin/': typeof CheckinIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/cycle/': typeof CycleIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/journey/': typeof JourneyIndexRoute
  '/mindfulness/': typeof MindfulnessIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/coaches/$id/book': typeof CoachesIdBookRoute
  '/coaches/$id/chat': typeof CoachesIdChatRoute
  '/workouts/$id/play': typeof WorkoutsIdPlayRoute
  '/workouts/programs/$id': typeof WorkoutsProgramsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/achievements': typeof AchievementsRoute
  '/assistant': typeof AssistantRoute
  '/bodyiq': typeof BodyiqRoute
  '/buddy': typeof BuddyRoute
  '/calendar': typeof CalendarRoute
  '/circle': typeof CircleRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/home-draft': typeof HomeDraftRoute
  '/paywall': typeof PaywallRoute
  '/pregnancy': typeof PregnancyRoute
  '/screens': typeof ScreensRoute
  '/search': typeof SearchRoute
  '/streak': typeof StreakRoute
  '/supplements': typeof SupplementsRoute
  '/system': typeof SystemRoute
  '/timer': typeof TimerRoute
  '/widgets': typeof WidgetsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/phase': typeof ChallengesPhaseRoute
  '/checkin/sleep': typeof CheckinSleepRoute
  '/checkin/steps': typeof CheckinStepsRoute
  '/checkin/water': typeof CheckinWaterRoute
  '/checkin/water-draft': typeof CheckinWaterDraftRoute
  '/coaches/$id': typeof CoachesIdRouteWithChildren
  '/community/$id': typeof CommunityIdRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/invite': typeof CommunityInviteRoute
  '/cycle/log': typeof CycleLogRoute
  '/habits/new': typeof HabitsNewRoute
  '/journey/awards': typeof JourneyAwardsRoute
  '/journey/calendar': typeof JourneyCalendarRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/insights': typeof JourneyInsightsRoute
  '/journey/measurements': typeof JourneyMeasurementsRoute
  '/journey/mood': typeof JourneyMoodRoute
  '/journey/symptoms': typeof JourneySymptomsRoute
  '/mindfulness/$id': typeof MindfulnessIdRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/nutrition/$id': typeof NutritionIdRoute
  '/nutrition/log': typeof NutritionLogRoute
  '/nutrition/recipes': typeof NutritionRecipesRoute
  '/nutrition/shopping': typeof NutritionShoppingRoute
  '/onboarding/activity': typeof OnboardingActivityRoute
  '/onboarding/auth': typeof OnboardingAuthRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/cycle-data': typeof OnboardingCycleDataRoute
  '/onboarding/diet': typeof OnboardingDietRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/frequency': typeof OnboardingFrequencyRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/level': typeof OnboardingLevelRoute
  '/onboarding/location-pref': typeof OnboardingLocationPrefRoute
  '/onboarding/nutrition-goal': typeof OnboardingNutritionGoalRoute
  '/onboarding/permissions': typeof OnboardingPermissionsRoute
  '/onboarding/stats': typeof OnboardingStatsRoute
  '/onboarding/trial': typeof OnboardingTrialRoute
  '/onboarding/types': typeof OnboardingTypesRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/delete': typeof ProfileDeleteRoute
  '/profile/devices': typeof ProfileDevicesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/export': typeof ProfileExportRoute
  '/profile/feedback': typeof ProfileFeedbackRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications-prefs': typeof ProfileNotificationsPrefsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/referral': typeof ProfileReferralRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/subscription': typeof ProfileSubscriptionRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/reports/$id': typeof ReportsIdRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/live': typeof WorkoutsLiveRoute
  '/workouts/programs': typeof WorkoutsProgramsRouteWithChildren
  '/workouts/summary': typeof WorkoutsSummaryRoute
  '/articles': typeof ArticlesIndexRoute
  '/challenges': typeof ChallengesIndexRoute
  '/checkin': typeof CheckinIndexRoute
  '/coaches': typeof CoachesIndexRoute
  '/community': typeof CommunityIndexRoute
  '/cycle': typeof CycleIndexRoute
  '/habits': typeof HabitsIndexRoute
  '/journey': typeof JourneyIndexRoute
  '/mindfulness': typeof MindfulnessIndexRoute
  '/notifications': typeof NotificationsIndexRoute
  '/nutrition': typeof NutritionIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/coaches/$id/book': typeof CoachesIdBookRoute
  '/coaches/$id/chat': typeof CoachesIdChatRoute
  '/workouts/$id/play': typeof WorkoutsIdPlayRoute
  '/workouts/programs/$id': typeof WorkoutsProgramsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/achievements': typeof AchievementsRoute
  '/assistant': typeof AssistantRoute
  '/bodyiq': typeof BodyiqRoute
  '/buddy': typeof BuddyRoute
  '/calendar': typeof CalendarRoute
  '/circle': typeof CircleRoute
  '/emergency': typeof EmergencyRoute
  '/home': typeof HomeRoute
  '/home-draft': typeof HomeDraftRoute
  '/paywall': typeof PaywallRoute
  '/pregnancy': typeof PregnancyRoute
  '/screens': typeof ScreensRoute
  '/search': typeof SearchRoute
  '/streak': typeof StreakRoute
  '/supplements': typeof SupplementsRoute
  '/system': typeof SystemRoute
  '/timer': typeof TimerRoute
  '/widgets': typeof WidgetsRoute
  '/articles/$id': typeof ArticlesIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/challenges/phase': typeof ChallengesPhaseRoute
  '/checkin/sleep': typeof CheckinSleepRoute
  '/checkin/steps': typeof CheckinStepsRoute
  '/checkin/water': typeof CheckinWaterRoute
  '/checkin/water-draft': typeof CheckinWaterDraftRoute
  '/coaches/$id': typeof CoachesIdRouteWithChildren
  '/community/$id': typeof CommunityIdRoute
  '/community/events': typeof CommunityEventsRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/invite': typeof CommunityInviteRoute
  '/cycle/log': typeof CycleLogRoute
  '/habits/new': typeof HabitsNewRoute
  '/journey/awards': typeof JourneyAwardsRoute
  '/journey/calendar': typeof JourneyCalendarRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/insights': typeof JourneyInsightsRoute
  '/journey/measurements': typeof JourneyMeasurementsRoute
  '/journey/mood': typeof JourneyMoodRoute
  '/journey/symptoms': typeof JourneySymptomsRoute
  '/mindfulness/$id': typeof MindfulnessIdRoute
  '/notifications/settings': typeof NotificationsSettingsRoute
  '/nutrition/$id': typeof NutritionIdRoute
  '/nutrition/log': typeof NutritionLogRoute
  '/nutrition/recipes': typeof NutritionRecipesRoute
  '/nutrition/shopping': typeof NutritionShoppingRoute
  '/onboarding/activity': typeof OnboardingActivityRoute
  '/onboarding/auth': typeof OnboardingAuthRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/cycle-data': typeof OnboardingCycleDataRoute
  '/onboarding/diet': typeof OnboardingDietRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/frequency': typeof OnboardingFrequencyRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/level': typeof OnboardingLevelRoute
  '/onboarding/location-pref': typeof OnboardingLocationPrefRoute
  '/onboarding/nutrition-goal': typeof OnboardingNutritionGoalRoute
  '/onboarding/permissions': typeof OnboardingPermissionsRoute
  '/onboarding/stats': typeof OnboardingStatsRoute
  '/onboarding/trial': typeof OnboardingTrialRoute
  '/onboarding/types': typeof OnboardingTypesRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/profile/about': typeof ProfileAboutRoute
  '/profile/backup': typeof ProfileBackupRoute
  '/profile/delete': typeof ProfileDeleteRoute
  '/profile/devices': typeof ProfileDevicesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/export': typeof ProfileExportRoute
  '/profile/feedback': typeof ProfileFeedbackRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/language': typeof ProfileLanguageRoute
  '/profile/notifications-prefs': typeof ProfileNotificationsPrefsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/referral': typeof ProfileReferralRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/subscription': typeof ProfileSubscriptionRoute
  '/profile/terms': typeof ProfileTermsRoute
  '/profile/theme': typeof ProfileThemeRoute
  '/reports/$id': typeof ReportsIdRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/live': typeof WorkoutsLiveRoute
  '/workouts/programs': typeof WorkoutsProgramsRouteWithChildren
  '/workouts/summary': typeof WorkoutsSummaryRoute
  '/articles/': typeof ArticlesIndexRoute
  '/challenges/': typeof ChallengesIndexRoute
  '/checkin/': typeof CheckinIndexRoute
  '/coaches/': typeof CoachesIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/cycle/': typeof CycleIndexRoute
  '/habits/': typeof HabitsIndexRoute
  '/journey/': typeof JourneyIndexRoute
  '/mindfulness/': typeof MindfulnessIndexRoute
  '/notifications/': typeof NotificationsIndexRoute
  '/nutrition/': typeof NutritionIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/coaches/$id/book': typeof CoachesIdBookRoute
  '/coaches/$id/chat': typeof CoachesIdChatRoute
  '/workouts/$id/play': typeof WorkoutsIdPlayRoute
  '/workouts/programs/$id': typeof WorkoutsProgramsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/achievements'
    | '/assistant'
    | '/bodyiq'
    | '/buddy'
    | '/calendar'
    | '/circle'
    | '/emergency'
    | '/home'
    | '/home-draft'
    | '/paywall'
    | '/pregnancy'
    | '/screens'
    | '/search'
    | '/streak'
    | '/supplements'
    | '/system'
    | '/timer'
    | '/widgets'
    | '/articles/$id'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/challenges/$id'
    | '/challenges/phase'
    | '/checkin/sleep'
    | '/checkin/steps'
    | '/checkin/water'
    | '/checkin/water-draft'
    | '/coaches/$id'
    | '/community/$id'
    | '/community/events'
    | '/community/groups'
    | '/community/invite'
    | '/cycle/log'
    | '/habits/new'
    | '/journey/awards'
    | '/journey/calendar'
    | '/journey/goals'
    | '/journey/insights'
    | '/journey/measurements'
    | '/journey/mood'
    | '/journey/symptoms'
    | '/mindfulness/$id'
    | '/notifications/settings'
    | '/nutrition/$id'
    | '/nutrition/log'
    | '/nutrition/recipes'
    | '/nutrition/shopping'
    | '/onboarding/activity'
    | '/onboarding/auth'
    | '/onboarding/complete'
    | '/onboarding/cycle-data'
    | '/onboarding/diet'
    | '/onboarding/dob'
    | '/onboarding/frequency'
    | '/onboarding/goal'
    | '/onboarding/level'
    | '/onboarding/location-pref'
    | '/onboarding/nutrition-goal'
    | '/onboarding/permissions'
    | '/onboarding/stats'
    | '/onboarding/trial'
    | '/onboarding/types'
    | '/onboarding/welcome'
    | '/profile/about'
    | '/profile/backup'
    | '/profile/delete'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/export'
    | '/profile/feedback'
    | '/profile/help'
    | '/profile/language'
    | '/profile/notifications-prefs'
    | '/profile/payment'
    | '/profile/privacy'
    | '/profile/referral'
    | '/profile/settings'
    | '/profile/subscription'
    | '/profile/terms'
    | '/profile/theme'
    | '/reports/$id'
    | '/workouts/$id'
    | '/workouts/live'
    | '/workouts/programs'
    | '/workouts/summary'
    | '/articles/'
    | '/challenges/'
    | '/checkin/'
    | '/coaches/'
    | '/community/'
    | '/cycle/'
    | '/habits/'
    | '/journey/'
    | '/mindfulness/'
    | '/notifications/'
    | '/nutrition/'
    | '/profile/'
    | '/reports/'
    | '/workouts/'
    | '/coaches/$id/book'
    | '/coaches/$id/chat'
    | '/workouts/$id/play'
    | '/workouts/programs/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/achievements'
    | '/assistant'
    | '/bodyiq'
    | '/buddy'
    | '/calendar'
    | '/circle'
    | '/emergency'
    | '/home'
    | '/home-draft'
    | '/paywall'
    | '/pregnancy'
    | '/screens'
    | '/search'
    | '/streak'
    | '/supplements'
    | '/system'
    | '/timer'
    | '/widgets'
    | '/articles/$id'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/challenges/$id'
    | '/challenges/phase'
    | '/checkin/sleep'
    | '/checkin/steps'
    | '/checkin/water'
    | '/checkin/water-draft'
    | '/coaches/$id'
    | '/community/$id'
    | '/community/events'
    | '/community/groups'
    | '/community/invite'
    | '/cycle/log'
    | '/habits/new'
    | '/journey/awards'
    | '/journey/calendar'
    | '/journey/goals'
    | '/journey/insights'
    | '/journey/measurements'
    | '/journey/mood'
    | '/journey/symptoms'
    | '/mindfulness/$id'
    | '/notifications/settings'
    | '/nutrition/$id'
    | '/nutrition/log'
    | '/nutrition/recipes'
    | '/nutrition/shopping'
    | '/onboarding/activity'
    | '/onboarding/auth'
    | '/onboarding/complete'
    | '/onboarding/cycle-data'
    | '/onboarding/diet'
    | '/onboarding/dob'
    | '/onboarding/frequency'
    | '/onboarding/goal'
    | '/onboarding/level'
    | '/onboarding/location-pref'
    | '/onboarding/nutrition-goal'
    | '/onboarding/permissions'
    | '/onboarding/stats'
    | '/onboarding/trial'
    | '/onboarding/types'
    | '/onboarding/welcome'
    | '/profile/about'
    | '/profile/backup'
    | '/profile/delete'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/export'
    | '/profile/feedback'
    | '/profile/help'
    | '/profile/language'
    | '/profile/notifications-prefs'
    | '/profile/payment'
    | '/profile/privacy'
    | '/profile/referral'
    | '/profile/settings'
    | '/profile/subscription'
    | '/profile/terms'
    | '/profile/theme'
    | '/reports/$id'
    | '/workouts/$id'
    | '/workouts/live'
    | '/workouts/programs'
    | '/workouts/summary'
    | '/articles'
    | '/challenges'
    | '/checkin'
    | '/coaches'
    | '/community'
    | '/cycle'
    | '/habits'
    | '/journey'
    | '/mindfulness'
    | '/notifications'
    | '/nutrition'
    | '/profile'
    | '/reports'
    | '/workouts'
    | '/coaches/$id/book'
    | '/coaches/$id/chat'
    | '/workouts/$id/play'
    | '/workouts/programs/$id'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/achievements'
    | '/assistant'
    | '/bodyiq'
    | '/buddy'
    | '/calendar'
    | '/circle'
    | '/emergency'
    | '/home'
    | '/home-draft'
    | '/paywall'
    | '/pregnancy'
    | '/screens'
    | '/search'
    | '/streak'
    | '/supplements'
    | '/system'
    | '/timer'
    | '/widgets'
    | '/articles/$id'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/challenges/$id'
    | '/challenges/phase'
    | '/checkin/sleep'
    | '/checkin/steps'
    | '/checkin/water'
    | '/checkin/water-draft'
    | '/coaches/$id'
    | '/community/$id'
    | '/community/events'
    | '/community/groups'
    | '/community/invite'
    | '/cycle/log'
    | '/habits/new'
    | '/journey/awards'
    | '/journey/calendar'
    | '/journey/goals'
    | '/journey/insights'
    | '/journey/measurements'
    | '/journey/mood'
    | '/journey/symptoms'
    | '/mindfulness/$id'
    | '/notifications/settings'
    | '/nutrition/$id'
    | '/nutrition/log'
    | '/nutrition/recipes'
    | '/nutrition/shopping'
    | '/onboarding/activity'
    | '/onboarding/auth'
    | '/onboarding/complete'
    | '/onboarding/cycle-data'
    | '/onboarding/diet'
    | '/onboarding/dob'
    | '/onboarding/frequency'
    | '/onboarding/goal'
    | '/onboarding/level'
    | '/onboarding/location-pref'
    | '/onboarding/nutrition-goal'
    | '/onboarding/permissions'
    | '/onboarding/stats'
    | '/onboarding/trial'
    | '/onboarding/types'
    | '/onboarding/welcome'
    | '/profile/about'
    | '/profile/backup'
    | '/profile/delete'
    | '/profile/devices'
    | '/profile/edit'
    | '/profile/export'
    | '/profile/feedback'
    | '/profile/help'
    | '/profile/language'
    | '/profile/notifications-prefs'
    | '/profile/payment'
    | '/profile/privacy'
    | '/profile/referral'
    | '/profile/settings'
    | '/profile/subscription'
    | '/profile/terms'
    | '/profile/theme'
    | '/reports/$id'
    | '/workouts/$id'
    | '/workouts/live'
    | '/workouts/programs'
    | '/workouts/summary'
    | '/articles/'
    | '/challenges/'
    | '/checkin/'
    | '/coaches/'
    | '/community/'
    | '/cycle/'
    | '/habits/'
    | '/journey/'
    | '/mindfulness/'
    | '/notifications/'
    | '/nutrition/'
    | '/profile/'
    | '/reports/'
    | '/workouts/'
    | '/coaches/$id/book'
    | '/coaches/$id/chat'
    | '/workouts/$id/play'
    | '/workouts/programs/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  AchievementsRoute: typeof AchievementsRoute
  AssistantRoute: typeof AssistantRoute
  BodyiqRoute: typeof BodyiqRoute
  BuddyRoute: typeof BuddyRoute
  CalendarRoute: typeof CalendarRoute
  CircleRoute: typeof CircleRoute
  EmergencyRoute: typeof EmergencyRoute
  HomeRoute: typeof HomeRoute
  HomeDraftRoute: typeof HomeDraftRoute
  PaywallRoute: typeof PaywallRoute
  PregnancyRoute: typeof PregnancyRoute
  ScreensRoute: typeof ScreensRoute
  SearchRoute: typeof SearchRoute
  StreakRoute: typeof StreakRoute
  SupplementsRoute: typeof SupplementsRoute
  SystemRoute: typeof SystemRoute
  TimerRoute: typeof TimerRoute
  WidgetsRoute: typeof WidgetsRoute
  ArticlesIdRoute: typeof ArticlesIdRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  ChallengesIdRoute: typeof ChallengesIdRoute
  ChallengesPhaseRoute: typeof ChallengesPhaseRoute
  CheckinSleepRoute: typeof CheckinSleepRoute
  CheckinStepsRoute: typeof CheckinStepsRoute
  CheckinWaterRoute: typeof CheckinWaterRoute
  CheckinWaterDraftRoute: typeof CheckinWaterDraftRoute
  CoachesIdRoute: typeof CoachesIdRouteWithChildren
  CommunityIdRoute: typeof CommunityIdRoute
  CommunityEventsRoute: typeof CommunityEventsRoute
  CommunityGroupsRoute: typeof CommunityGroupsRoute
  CommunityInviteRoute: typeof CommunityInviteRoute
  CycleLogRoute: typeof CycleLogRoute
  HabitsNewRoute: typeof HabitsNewRoute
  JourneyAwardsRoute: typeof JourneyAwardsRoute
  JourneyCalendarRoute: typeof JourneyCalendarRoute
  JourneyGoalsRoute: typeof JourneyGoalsRoute
  JourneyInsightsRoute: typeof JourneyInsightsRoute
  JourneyMeasurementsRoute: typeof JourneyMeasurementsRoute
  JourneyMoodRoute: typeof JourneyMoodRoute
  JourneySymptomsRoute: typeof JourneySymptomsRoute
  MindfulnessIdRoute: typeof MindfulnessIdRoute
  NotificationsSettingsRoute: typeof NotificationsSettingsRoute
  NutritionIdRoute: typeof NutritionIdRoute
  NutritionLogRoute: typeof NutritionLogRoute
  NutritionRecipesRoute: typeof NutritionRecipesRoute
  NutritionShoppingRoute: typeof NutritionShoppingRoute
  OnboardingActivityRoute: typeof OnboardingActivityRoute
  OnboardingAuthRoute: typeof OnboardingAuthRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingCycleDataRoute: typeof OnboardingCycleDataRoute
  OnboardingDietRoute: typeof OnboardingDietRoute
  OnboardingDobRoute: typeof OnboardingDobRoute
  OnboardingFrequencyRoute: typeof OnboardingFrequencyRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingLevelRoute: typeof OnboardingLevelRoute
  OnboardingLocationPrefRoute: typeof OnboardingLocationPrefRoute
  OnboardingNutritionGoalRoute: typeof OnboardingNutritionGoalRoute
  OnboardingPermissionsRoute: typeof OnboardingPermissionsRoute
  OnboardingStatsRoute: typeof OnboardingStatsRoute
  OnboardingTrialRoute: typeof OnboardingTrialRoute
  OnboardingTypesRoute: typeof OnboardingTypesRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  ProfileAboutRoute: typeof ProfileAboutRoute
  ProfileBackupRoute: typeof ProfileBackupRoute
  ProfileDeleteRoute: typeof ProfileDeleteRoute
  ProfileDevicesRoute: typeof ProfileDevicesRoute
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileExportRoute: typeof ProfileExportRoute
  ProfileFeedbackRoute: typeof ProfileFeedbackRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileLanguageRoute: typeof ProfileLanguageRoute
  ProfileNotificationsPrefsRoute: typeof ProfileNotificationsPrefsRoute
  ProfilePaymentRoute: typeof ProfilePaymentRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileReferralRoute: typeof ProfileReferralRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSubscriptionRoute: typeof ProfileSubscriptionRoute
  ProfileTermsRoute: typeof ProfileTermsRoute
  ProfileThemeRoute: typeof ProfileThemeRoute
  ReportsIdRoute: typeof ReportsIdRoute
  WorkoutsIdRoute: typeof WorkoutsIdRouteWithChildren
  WorkoutsLiveRoute: typeof WorkoutsLiveRoute
  WorkoutsProgramsRoute: typeof WorkoutsProgramsRouteWithChildren
  WorkoutsSummaryRoute: typeof WorkoutsSummaryRoute
  ArticlesIndexRoute: typeof ArticlesIndexRoute
  ChallengesIndexRoute: typeof ChallengesIndexRoute
  CheckinIndexRoute: typeof CheckinIndexRoute
  CoachesIndexRoute: typeof CoachesIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
  CycleIndexRoute: typeof CycleIndexRoute
  HabitsIndexRoute: typeof HabitsIndexRoute
  JourneyIndexRoute: typeof JourneyIndexRoute
  MindfulnessIndexRoute: typeof MindfulnessIndexRoute
  NotificationsIndexRoute: typeof NotificationsIndexRoute
  NutritionIndexRoute: typeof NutritionIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/widgets': {
      id: '/widgets'
      path: '/widgets'
      fullPath: '/widgets'
      preLoaderRoute: typeof WidgetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements': {
      id: '/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof SupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/streak': {
      id: '/streak'
      path: '/streak'
      fullPath: '/streak'
      preLoaderRoute: typeof StreakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregnancy': {
      id: '/pregnancy'
      path: '/pregnancy'
      fullPath: '/pregnancy'
      preLoaderRoute: typeof PregnancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home-draft': {
      id: '/home-draft'
      path: '/home-draft'
      fullPath: '/home-draft'
      preLoaderRoute: typeof HomeDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buddy': {
      id: '/buddy'
      path: '/buddy'
      fullPath: '/buddy'
      preLoaderRoute: typeof BuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bodyiq': {
      id: '/bodyiq'
      path: '/bodyiq'
      fullPath: '/bodyiq'
      preLoaderRoute: typeof BodyiqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/workouts'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/': {
      id: '/nutrition/'
      path: '/nutrition'
      fullPath: '/nutrition/'
      preLoaderRoute: typeof NutritionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/': {
      id: '/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof NotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindfulness/': {
      id: '/mindfulness/'
      path: '/mindfulness'
      fullPath: '/mindfulness/'
      preLoaderRoute: typeof MindfulnessIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/': {
      id: '/journey/'
      path: '/journey'
      fullPath: '/journey/'
      preLoaderRoute: typeof JourneyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/': {
      id: '/habits/'
      path: '/habits'
      fullPath: '/habits/'
      preLoaderRoute: typeof HabitsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle/': {
      id: '/cycle/'
      path: '/cycle'
      fullPath: '/cycle/'
      preLoaderRoute: typeof CycleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/': {
      id: '/coaches/'
      path: '/coaches'
      fullPath: '/coaches/'
      preLoaderRoute: typeof CoachesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/': {
      id: '/checkin/'
      path: '/checkin'
      fullPath: '/checkin/'
      preLoaderRoute: typeof CheckinIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/': {
      id: '/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof ChallengesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/': {
      id: '/articles/'
      path: '/articles'
      fullPath: '/articles/'
      preLoaderRoute: typeof ArticlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/summary': {
      id: '/workouts/summary'
      path: '/workouts/summary'
      fullPath: '/workouts/summary'
      preLoaderRoute: typeof WorkoutsSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/programs': {
      id: '/workouts/programs'
      path: '/workouts/programs'
      fullPath: '/workouts/programs'
      preLoaderRoute: typeof WorkoutsProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/live': {
      id: '/workouts/live'
      path: '/workouts/live'
      fullPath: '/workouts/live'
      preLoaderRoute: typeof WorkoutsLiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/workouts/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/theme': {
      id: '/profile/theme'
      path: '/profile/theme'
      fullPath: '/profile/theme'
      preLoaderRoute: typeof ProfileThemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/terms': {
      id: '/profile/terms'
      path: '/profile/terms'
      fullPath: '/profile/terms'
      preLoaderRoute: typeof ProfileTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/subscription': {
      id: '/profile/subscription'
      path: '/profile/subscription'
      fullPath: '/profile/subscription'
      preLoaderRoute: typeof ProfileSubscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/profile/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/referral': {
      id: '/profile/referral'
      path: '/profile/referral'
      fullPath: '/profile/referral'
      preLoaderRoute: typeof ProfileReferralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/profile/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/payment': {
      id: '/profile/payment'
      path: '/profile/payment'
      fullPath: '/profile/payment'
      preLoaderRoute: typeof ProfilePaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/notifications-prefs': {
      id: '/profile/notifications-prefs'
      path: '/profile/notifications-prefs'
      fullPath: '/profile/notifications-prefs'
      preLoaderRoute: typeof ProfileNotificationsPrefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/language': {
      id: '/profile/language'
      path: '/profile/language'
      fullPath: '/profile/language'
      preLoaderRoute: typeof ProfileLanguageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/profile/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/feedback': {
      id: '/profile/feedback'
      path: '/profile/feedback'
      fullPath: '/profile/feedback'
      preLoaderRoute: typeof ProfileFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/export': {
      id: '/profile/export'
      path: '/profile/export'
      fullPath: '/profile/export'
      preLoaderRoute: typeof ProfileExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/devices': {
      id: '/profile/devices'
      path: '/profile/devices'
      fullPath: '/profile/devices'
      preLoaderRoute: typeof ProfileDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/delete': {
      id: '/profile/delete'
      path: '/profile/delete'
      fullPath: '/profile/delete'
      preLoaderRoute: typeof ProfileDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/backup': {
      id: '/profile/backup'
      path: '/profile/backup'
      fullPath: '/profile/backup'
      preLoaderRoute: typeof ProfileBackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/about': {
      id: '/profile/about'
      path: '/profile/about'
      fullPath: '/profile/about'
      preLoaderRoute: typeof ProfileAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/types': {
      id: '/onboarding/types'
      path: '/onboarding/types'
      fullPath: '/onboarding/types'
      preLoaderRoute: typeof OnboardingTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/trial': {
      id: '/onboarding/trial'
      path: '/onboarding/trial'
      fullPath: '/onboarding/trial'
      preLoaderRoute: typeof OnboardingTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/stats': {
      id: '/onboarding/stats'
      path: '/onboarding/stats'
      fullPath: '/onboarding/stats'
      preLoaderRoute: typeof OnboardingStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/permissions': {
      id: '/onboarding/permissions'
      path: '/onboarding/permissions'
      fullPath: '/onboarding/permissions'
      preLoaderRoute: typeof OnboardingPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/nutrition-goal': {
      id: '/onboarding/nutrition-goal'
      path: '/onboarding/nutrition-goal'
      fullPath: '/onboarding/nutrition-goal'
      preLoaderRoute: typeof OnboardingNutritionGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/location-pref': {
      id: '/onboarding/location-pref'
      path: '/onboarding/location-pref'
      fullPath: '/onboarding/location-pref'
      preLoaderRoute: typeof OnboardingLocationPrefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/level': {
      id: '/onboarding/level'
      path: '/onboarding/level'
      fullPath: '/onboarding/level'
      preLoaderRoute: typeof OnboardingLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/frequency': {
      id: '/onboarding/frequency'
      path: '/onboarding/frequency'
      fullPath: '/onboarding/frequency'
      preLoaderRoute: typeof OnboardingFrequencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/dob': {
      id: '/onboarding/dob'
      path: '/onboarding/dob'
      fullPath: '/onboarding/dob'
      preLoaderRoute: typeof OnboardingDobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/diet': {
      id: '/onboarding/diet'
      path: '/onboarding/diet'
      fullPath: '/onboarding/diet'
      preLoaderRoute: typeof OnboardingDietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/cycle-data': {
      id: '/onboarding/cycle-data'
      path: '/onboarding/cycle-data'
      fullPath: '/onboarding/cycle-data'
      preLoaderRoute: typeof OnboardingCycleDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/auth': {
      id: '/onboarding/auth'
      path: '/onboarding/auth'
      fullPath: '/onboarding/auth'
      preLoaderRoute: typeof OnboardingAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/activity': {
      id: '/onboarding/activity'
      path: '/onboarding/activity'
      fullPath: '/onboarding/activity'
      preLoaderRoute: typeof OnboardingActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/shopping': {
      id: '/nutrition/shopping'
      path: '/nutrition/shopping'
      fullPath: '/nutrition/shopping'
      preLoaderRoute: typeof NutritionShoppingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/recipes': {
      id: '/nutrition/recipes'
      path: '/nutrition/recipes'
      fullPath: '/nutrition/recipes'
      preLoaderRoute: typeof NutritionRecipesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/log': {
      id: '/nutrition/log'
      path: '/nutrition/log'
      fullPath: '/nutrition/log'
      preLoaderRoute: typeof NutritionLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/$id': {
      id: '/nutrition/$id'
      path: '/nutrition/$id'
      fullPath: '/nutrition/$id'
      preLoaderRoute: typeof NutritionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications/settings': {
      id: '/notifications/settings'
      path: '/notifications/settings'
      fullPath: '/notifications/settings'
      preLoaderRoute: typeof NotificationsSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindfulness/$id': {
      id: '/mindfulness/$id'
      path: '/mindfulness/$id'
      fullPath: '/mindfulness/$id'
      preLoaderRoute: typeof MindfulnessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/symptoms': {
      id: '/journey/symptoms'
      path: '/journey/symptoms'
      fullPath: '/journey/symptoms'
      preLoaderRoute: typeof JourneySymptomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/mood': {
      id: '/journey/mood'
      path: '/journey/mood'
      fullPath: '/journey/mood'
      preLoaderRoute: typeof JourneyMoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/measurements': {
      id: '/journey/measurements'
      path: '/journey/measurements'
      fullPath: '/journey/measurements'
      preLoaderRoute: typeof JourneyMeasurementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/insights': {
      id: '/journey/insights'
      path: '/journey/insights'
      fullPath: '/journey/insights'
      preLoaderRoute: typeof JourneyInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/goals': {
      id: '/journey/goals'
      path: '/journey/goals'
      fullPath: '/journey/goals'
      preLoaderRoute: typeof JourneyGoalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/calendar': {
      id: '/journey/calendar'
      path: '/journey/calendar'
      fullPath: '/journey/calendar'
      preLoaderRoute: typeof JourneyCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey/awards': {
      id: '/journey/awards'
      path: '/journey/awards'
      fullPath: '/journey/awards'
      preLoaderRoute: typeof JourneyAwardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits/new': {
      id: '/habits/new'
      path: '/habits/new'
      fullPath: '/habits/new'
      preLoaderRoute: typeof HabitsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle/log': {
      id: '/cycle/log'
      path: '/cycle/log'
      fullPath: '/cycle/log'
      preLoaderRoute: typeof CycleLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/invite': {
      id: '/community/invite'
      path: '/community/invite'
      fullPath: '/community/invite'
      preLoaderRoute: typeof CommunityInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/groups': {
      id: '/community/groups'
      path: '/community/groups'
      fullPath: '/community/groups'
      preLoaderRoute: typeof CommunityGroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/events': {
      id: '/community/events'
      path: '/community/events'
      fullPath: '/community/events'
      preLoaderRoute: typeof CommunityEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/community/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches/$id': {
      id: '/coaches/$id'
      path: '/coaches/$id'
      fullPath: '/coaches/$id'
      preLoaderRoute: typeof CoachesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/water-draft': {
      id: '/checkin/water-draft'
      path: '/checkin/water-draft'
      fullPath: '/checkin/water-draft'
      preLoaderRoute: typeof CheckinWaterDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/water': {
      id: '/checkin/water'
      path: '/checkin/water'
      fullPath: '/checkin/water'
      preLoaderRoute: typeof CheckinWaterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/steps': {
      id: '/checkin/steps'
      path: '/checkin/steps'
      fullPath: '/checkin/steps'
      preLoaderRoute: typeof CheckinStepsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin/sleep': {
      id: '/checkin/sleep'
      path: '/checkin/sleep'
      fullPath: '/checkin/sleep'
      preLoaderRoute: typeof CheckinSleepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/phase': {
      id: '/challenges/phase'
      path: '/challenges/phase'
      fullPath: '/challenges/phase'
      preLoaderRoute: typeof ChallengesPhaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/new-password': {
      id: '/auth/new-password'
      path: '/auth/new-password'
      fullPath: '/auth/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/articles/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/programs/$id': {
      id: '/workouts/programs/$id'
      path: '/$id'
      fullPath: '/workouts/programs/$id'
      preLoaderRoute: typeof WorkoutsProgramsIdRouteImport
      parentRoute: typeof WorkoutsProgramsRoute
    }
    '/workouts/$id/play': {
      id: '/workouts/$id/play'
      path: '/play'
      fullPath: '/workouts/$id/play'
      preLoaderRoute: typeof WorkoutsIdPlayRouteImport
      parentRoute: typeof WorkoutsIdRoute
    }
    '/coaches/$id/chat': {
      id: '/coaches/$id/chat'
      path: '/chat'
      fullPath: '/coaches/$id/chat'
      preLoaderRoute: typeof CoachesIdChatRouteImport
      parentRoute: typeof CoachesIdRoute
    }
    '/coaches/$id/book': {
      id: '/coaches/$id/book'
      path: '/book'
      fullPath: '/coaches/$id/book'
      preLoaderRoute: typeof CoachesIdBookRouteImport
      parentRoute: typeof CoachesIdRoute
    }
  }
}

interface CoachesIdRouteChildren {
  CoachesIdBookRoute: typeof CoachesIdBookRoute
  CoachesIdChatRoute: typeof CoachesIdChatRoute
}

const CoachesIdRouteChildren: CoachesIdRouteChildren = {
  CoachesIdBookRoute: CoachesIdBookRoute,
  CoachesIdChatRoute: CoachesIdChatRoute,
}

const CoachesIdRouteWithChildren = CoachesIdRoute._addFileChildren(
  CoachesIdRouteChildren,
)

interface WorkoutsIdRouteChildren {
  WorkoutsIdPlayRoute: typeof WorkoutsIdPlayRoute
}

const WorkoutsIdRouteChildren: WorkoutsIdRouteChildren = {
  WorkoutsIdPlayRoute: WorkoutsIdPlayRoute,
}

const WorkoutsIdRouteWithChildren = WorkoutsIdRoute._addFileChildren(
  WorkoutsIdRouteChildren,
)

interface WorkoutsProgramsRouteChildren {
  WorkoutsProgramsIdRoute: typeof WorkoutsProgramsIdRoute
}

const WorkoutsProgramsRouteChildren: WorkoutsProgramsRouteChildren = {
  WorkoutsProgramsIdRoute: WorkoutsProgramsIdRoute,
}

const WorkoutsProgramsRouteWithChildren =
  WorkoutsProgramsRoute._addFileChildren(WorkoutsProgramsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  AchievementsRoute: AchievementsRoute,
  AssistantRoute: AssistantRoute,
  BodyiqRoute: BodyiqRoute,
  BuddyRoute: BuddyRoute,
  CalendarRoute: CalendarRoute,
  CircleRoute: CircleRoute,
  EmergencyRoute: EmergencyRoute,
  HomeRoute: HomeRoute,
  HomeDraftRoute: HomeDraftRoute,
  PaywallRoute: PaywallRoute,
  PregnancyRoute: PregnancyRoute,
  ScreensRoute: ScreensRoute,
  SearchRoute: SearchRoute,
  StreakRoute: StreakRoute,
  SupplementsRoute: SupplementsRoute,
  SystemRoute: SystemRoute,
  TimerRoute: TimerRoute,
  WidgetsRoute: WidgetsRoute,
  ArticlesIdRoute: ArticlesIdRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  ChallengesIdRoute: ChallengesIdRoute,
  ChallengesPhaseRoute: ChallengesPhaseRoute,
  CheckinSleepRoute: CheckinSleepRoute,
  CheckinStepsRoute: CheckinStepsRoute,
  CheckinWaterRoute: CheckinWaterRoute,
  CheckinWaterDraftRoute: CheckinWaterDraftRoute,
  CoachesIdRoute: CoachesIdRouteWithChildren,
  CommunityIdRoute: CommunityIdRoute,
  CommunityEventsRoute: CommunityEventsRoute,
  CommunityGroupsRoute: CommunityGroupsRoute,
  CommunityInviteRoute: CommunityInviteRoute,
  CycleLogRoute: CycleLogRoute,
  HabitsNewRoute: HabitsNewRoute,
  JourneyAwardsRoute: JourneyAwardsRoute,
  JourneyCalendarRoute: JourneyCalendarRoute,
  JourneyGoalsRoute: JourneyGoalsRoute,
  JourneyInsightsRoute: JourneyInsightsRoute,
  JourneyMeasurementsRoute: JourneyMeasurementsRoute,
  JourneyMoodRoute: JourneyMoodRoute,
  JourneySymptomsRoute: JourneySymptomsRoute,
  MindfulnessIdRoute: MindfulnessIdRoute,
  NotificationsSettingsRoute: NotificationsSettingsRoute,
  NutritionIdRoute: NutritionIdRoute,
  NutritionLogRoute: NutritionLogRoute,
  NutritionRecipesRoute: NutritionRecipesRoute,
  NutritionShoppingRoute: NutritionShoppingRoute,
  OnboardingActivityRoute: OnboardingActivityRoute,
  OnboardingAuthRoute: OnboardingAuthRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingCycleDataRoute: OnboardingCycleDataRoute,
  OnboardingDietRoute: OnboardingDietRoute,
  OnboardingDobRoute: OnboardingDobRoute,
  OnboardingFrequencyRoute: OnboardingFrequencyRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingLevelRoute: OnboardingLevelRoute,
  OnboardingLocationPrefRoute: OnboardingLocationPrefRoute,
  OnboardingNutritionGoalRoute: OnboardingNutritionGoalRoute,
  OnboardingPermissionsRoute: OnboardingPermissionsRoute,
  OnboardingStatsRoute: OnboardingStatsRoute,
  OnboardingTrialRoute: OnboardingTrialRoute,
  OnboardingTypesRoute: OnboardingTypesRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  ProfileAboutRoute: ProfileAboutRoute,
  ProfileBackupRoute: ProfileBackupRoute,
  ProfileDeleteRoute: ProfileDeleteRoute,
  ProfileDevicesRoute: ProfileDevicesRoute,
  ProfileEditRoute: ProfileEditRoute,
  ProfileExportRoute: ProfileExportRoute,
  ProfileFeedbackRoute: ProfileFeedbackRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileLanguageRoute: ProfileLanguageRoute,
  ProfileNotificationsPrefsRoute: ProfileNotificationsPrefsRoute,
  ProfilePaymentRoute: ProfilePaymentRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileReferralRoute: ProfileReferralRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSubscriptionRoute: ProfileSubscriptionRoute,
  ProfileTermsRoute: ProfileTermsRoute,
  ProfileThemeRoute: ProfileThemeRoute,
  ReportsIdRoute: ReportsIdRoute,
  WorkoutsIdRoute: WorkoutsIdRouteWithChildren,
  WorkoutsLiveRoute: WorkoutsLiveRoute,
  WorkoutsProgramsRoute: WorkoutsProgramsRouteWithChildren,
  WorkoutsSummaryRoute: WorkoutsSummaryRoute,
  ArticlesIndexRoute: ArticlesIndexRoute,
  ChallengesIndexRoute: ChallengesIndexRoute,
  CheckinIndexRoute: CheckinIndexRoute,
  CoachesIndexRoute: CoachesIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
  CycleIndexRoute: CycleIndexRoute,
  HabitsIndexRoute: HabitsIndexRoute,
  JourneyIndexRoute: JourneyIndexRoute,
  MindfulnessIndexRoute: MindfulnessIndexRoute,
  NotificationsIndexRoute: NotificationsIndexRoute,
  NutritionIndexRoute: NutritionIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
