/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as SystemRouteImport } from './routes/system'
import { Route as SupplementsRouteImport } from './routes/supplements'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PregnancyRouteImport } from './routes/pregnancy'
import { Route as PaywallRouteImport } from './routes/paywall'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MindfulnessRouteImport } from './routes/mindfulness'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as HomeRouteImport } from './routes/home'
import { Route as CycleRouteImport } from './routes/cycle'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as ChallengesRouteImport } from './routes/challenges'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as ArticlesRouteImport } from './routes/articles'
import { Route as R404RouteImport } from './routes/404'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsSummaryRouteImport } from './routes/workouts.summary'
import { Route as WorkoutsProgramsRouteImport } from './routes/workouts.programs'
import { Route as WorkoutsLiveRouteImport } from './routes/workouts.live'
import { Route as WorkoutsIdRouteImport } from './routes/workouts.$id'
import { Route as ProfileSubscriptionRouteImport } from './routes/profile.subscription'
import { Route as ProfileSettingsRouteImport } from './routes/profile.settings'
import { Route as ProfilePrivacyRouteImport } from './routes/profile.privacy'
import { Route as ProfilePaymentRouteImport } from './routes/profile.payment'
import { Route as ProfileNotificationsPrefsRouteImport } from './routes/profile.notifications-prefs'
import { Route as ProfileHelpRouteImport } from './routes/profile.help'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingTypesRouteImport } from './routes/onboarding.types'
import { Route as OnboardingTrialRouteImport } from './routes/onboarding.trial'
import { Route as OnboardingStatsRouteImport } from './routes/onboarding.stats'
import { Route as OnboardingPermissionsRouteImport } from './routes/onboarding.permissions'
import { Route as OnboardingNutritionGoalRouteImport } from './routes/onboarding.nutrition-goal'
import { Route as OnboardingLocationPrefRouteImport } from './routes/onboarding.location-pref'
import { Route as OnboardingLevelRouteImport } from './routes/onboarding.level'
import { Route as OnboardingGoalRouteImport } from './routes/onboarding.goal'
import { Route as OnboardingFrequencyRouteImport } from './routes/onboarding.frequency'
import { Route as OnboardingDobRouteImport } from './routes/onboarding.dob'
import { Route as OnboardingDietRouteImport } from './routes/onboarding.diet'
import { Route as OnboardingCycleDataRouteImport } from './routes/onboarding.cycle-data'
import { Route as OnboardingCompleteRouteImport } from './routes/onboarding.complete'
import { Route as OnboardingAuthRouteImport } from './routes/onboarding.auth'
import { Route as OnboardingActivityRouteImport } from './routes/onboarding.activity'
import { Route as NutritionRecipesRouteImport } from './routes/nutrition.recipes'
import { Route as NutritionLogRouteImport } from './routes/nutrition.log'
import { Route as NutritionIdRouteImport } from './routes/nutrition.$id'
import { Route as MindfulnessIdRouteImport } from './routes/mindfulness.$id'
import { Route as JourneySymptomsRouteImport } from './routes/journey.symptoms'
import { Route as JourneyMoodRouteImport } from './routes/journey.mood'
import { Route as JourneyMeasurementsRouteImport } from './routes/journey.measurements'
import { Route as JourneyInsightsRouteImport } from './routes/journey.insights'
import { Route as JourneyGoalsRouteImport } from './routes/journey.goals'
import { Route as JourneyAwardsRouteImport } from './routes/journey.awards'
import { Route as CycleLogRouteImport } from './routes/cycle.log'
import { Route as CommunityInviteRouteImport } from './routes/community.invite'
import { Route as CommunityGroupsRouteImport } from './routes/community.groups'
import { Route as CommunityIdRouteImport } from './routes/community.$id'
import { Route as CoachesIdRouteImport } from './routes/coaches.$id'
import { Route as CheckinWaterRouteImport } from './routes/checkin.water'
import { Route as CheckinStepsRouteImport } from './routes/checkin.steps'
import { Route as CheckinSleepRouteImport } from './routes/checkin.sleep'
import { Route as ChallengesIdRouteImport } from './routes/challenges.$id'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthNewPasswordRouteImport } from './routes/auth.new-password'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as ArticlesIdRouteImport } from './routes/articles.$id'
import { Route as WorkoutsIdPlayRouteImport } from './routes/workouts.$id.play'
import { Route as CoachesIdChatRouteImport } from './routes/coaches.$id.chat'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplementsRoute = SupplementsRouteImport.update({
  id: '/supplements',
  path: '/supplements',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PregnancyRoute = PregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => rootRouteImport,
} as any)
const PaywallRoute = PaywallRouteImport.update({
  id: '/paywall',
  path: '/paywall',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MindfulnessRoute = MindfulnessRouteImport.update({
  id: '/mindfulness',
  path: '/mindfulness',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CycleRoute = CycleRouteImport.update({
  id: '/cycle',
  path: '/cycle',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengesRoute = ChallengesRouteImport.update({
  id: '/challenges',
  path: '/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesRoute = ArticlesRouteImport.update({
  id: '/articles',
  path: '/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const R404Route = R404RouteImport.update({
  id: '/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsSummaryRoute = WorkoutsSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsProgramsRoute = WorkoutsProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsLiveRoute = WorkoutsLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsIdRoute = WorkoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => WorkoutsRoute,
} as any)
const ProfileSubscriptionRoute = ProfileSubscriptionRouteImport.update({
  id: '/subscription',
  path: '/subscription',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileSettingsRoute = ProfileSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePrivacyRoute = ProfilePrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfilePaymentRoute = ProfilePaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileNotificationsPrefsRoute =
  ProfileNotificationsPrefsRouteImport.update({
    id: '/notifications-prefs',
    path: '/notifications-prefs',
    getParentRoute: () => ProfileRoute,
  } as any)
const ProfileHelpRoute = ProfileHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => ProfileRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/onboarding/welcome',
  path: '/onboarding/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTypesRoute = OnboardingTypesRouteImport.update({
  id: '/onboarding/types',
  path: '/onboarding/types',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingTrialRoute = OnboardingTrialRouteImport.update({
  id: '/onboarding/trial',
  path: '/onboarding/trial',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingStatsRoute = OnboardingStatsRouteImport.update({
  id: '/onboarding/stats',
  path: '/onboarding/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingPermissionsRoute = OnboardingPermissionsRouteImport.update({
  id: '/onboarding/permissions',
  path: '/onboarding/permissions',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingNutritionGoalRoute = OnboardingNutritionGoalRouteImport.update({
  id: '/onboarding/nutrition-goal',
  path: '/onboarding/nutrition-goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLocationPrefRoute = OnboardingLocationPrefRouteImport.update({
  id: '/onboarding/location-pref',
  path: '/onboarding/location-pref',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingLevelRoute = OnboardingLevelRouteImport.update({
  id: '/onboarding/level',
  path: '/onboarding/level',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingGoalRoute = OnboardingGoalRouteImport.update({
  id: '/onboarding/goal',
  path: '/onboarding/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingFrequencyRoute = OnboardingFrequencyRouteImport.update({
  id: '/onboarding/frequency',
  path: '/onboarding/frequency',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDobRoute = OnboardingDobRouteImport.update({
  id: '/onboarding/dob',
  path: '/onboarding/dob',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingDietRoute = OnboardingDietRouteImport.update({
  id: '/onboarding/diet',
  path: '/onboarding/diet',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCycleDataRoute = OnboardingCycleDataRouteImport.update({
  id: '/onboarding/cycle-data',
  path: '/onboarding/cycle-data',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCompleteRoute = OnboardingCompleteRouteImport.update({
  id: '/onboarding/complete',
  path: '/onboarding/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingAuthRoute = OnboardingAuthRouteImport.update({
  id: '/onboarding/auth',
  path: '/onboarding/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingActivityRoute = OnboardingActivityRouteImport.update({
  id: '/onboarding/activity',
  path: '/onboarding/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRecipesRoute = NutritionRecipesRouteImport.update({
  id: '/recipes',
  path: '/recipes',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionLogRoute = NutritionLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => NutritionRoute,
} as any)
const NutritionIdRoute = NutritionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NutritionRoute,
} as any)
const MindfulnessIdRoute = MindfulnessIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MindfulnessRoute,
} as any)
const JourneySymptomsRoute = JourneySymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyMoodRoute = JourneyMoodRouteImport.update({
  id: '/mood',
  path: '/mood',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyMeasurementsRoute = JourneyMeasurementsRouteImport.update({
  id: '/measurements',
  path: '/measurements',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyInsightsRoute = JourneyInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyGoalsRoute = JourneyGoalsRouteImport.update({
  id: '/goals',
  path: '/goals',
  getParentRoute: () => JourneyRoute,
} as any)
const JourneyAwardsRoute = JourneyAwardsRouteImport.update({
  id: '/awards',
  path: '/awards',
  getParentRoute: () => JourneyRoute,
} as any)
const CycleLogRoute = CycleLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => CycleRoute,
} as any)
const CommunityInviteRoute = CommunityInviteRouteImport.update({
  id: '/invite',
  path: '/invite',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityGroupsRoute = CommunityGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => CommunityRoute,
} as any)
const CommunityIdRoute = CommunityIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CommunityRoute,
} as any)
const CoachesIdRoute = CoachesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CoachesRoute,
} as any)
const CheckinWaterRoute = CheckinWaterRouteImport.update({
  id: '/water',
  path: '/water',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinStepsRoute = CheckinStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinSleepRoute = CheckinSleepRouteImport.update({
  id: '/sleep',
  path: '/sleep',
  getParentRoute: () => CheckinRoute,
} as any)
const ChallengesIdRoute = ChallengesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChallengesRoute,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthNewPasswordRoute = AuthNewPasswordRouteImport.update({
  id: '/auth/new-password',
  path: '/auth/new-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticlesIdRoute = ArticlesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArticlesRoute,
} as any)
const WorkoutsIdPlayRoute = WorkoutsIdPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => WorkoutsIdRoute,
} as any)
const CoachesIdChatRoute = CoachesIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => CoachesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/articles': typeof ArticlesRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/checkin': typeof CheckinRouteWithChildren
  '/coaches': typeof CoachesRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/cycle': typeof CycleRouteWithChildren
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRouteWithChildren
  '/mindfulness': typeof MindfulnessRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/pregnancy': typeof PregnancyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/screens': typeof ScreensRoute
  '/search': typeof SearchRoute
  '/supplements': typeof SupplementsRoute
  '/system': typeof SystemRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/checkin/sleep': typeof CheckinSleepRoute
  '/checkin/steps': typeof CheckinStepsRoute
  '/checkin/water': typeof CheckinWaterRoute
  '/coaches/$id': typeof CoachesIdRouteWithChildren
  '/community/$id': typeof CommunityIdRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/invite': typeof CommunityInviteRoute
  '/cycle/log': typeof CycleLogRoute
  '/journey/awards': typeof JourneyAwardsRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/insights': typeof JourneyInsightsRoute
  '/journey/measurements': typeof JourneyMeasurementsRoute
  '/journey/mood': typeof JourneyMoodRoute
  '/journey/symptoms': typeof JourneySymptomsRoute
  '/mindfulness/$id': typeof MindfulnessIdRoute
  '/nutrition/$id': typeof NutritionIdRoute
  '/nutrition/log': typeof NutritionLogRoute
  '/nutrition/recipes': typeof NutritionRecipesRoute
  '/onboarding/activity': typeof OnboardingActivityRoute
  '/onboarding/auth': typeof OnboardingAuthRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/cycle-data': typeof OnboardingCycleDataRoute
  '/onboarding/diet': typeof OnboardingDietRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/frequency': typeof OnboardingFrequencyRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/level': typeof OnboardingLevelRoute
  '/onboarding/location-pref': typeof OnboardingLocationPrefRoute
  '/onboarding/nutrition-goal': typeof OnboardingNutritionGoalRoute
  '/onboarding/permissions': typeof OnboardingPermissionsRoute
  '/onboarding/stats': typeof OnboardingStatsRoute
  '/onboarding/trial': typeof OnboardingTrialRoute
  '/onboarding/types': typeof OnboardingTypesRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/notifications-prefs': typeof ProfileNotificationsPrefsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/subscription': typeof ProfileSubscriptionRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/live': typeof WorkoutsLiveRoute
  '/workouts/programs': typeof WorkoutsProgramsRoute
  '/workouts/summary': typeof WorkoutsSummaryRoute
  '/coaches/$id/chat': typeof CoachesIdChatRoute
  '/workouts/$id/play': typeof WorkoutsIdPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/articles': typeof ArticlesRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/checkin': typeof CheckinRouteWithChildren
  '/coaches': typeof CoachesRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/cycle': typeof CycleRouteWithChildren
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRouteWithChildren
  '/mindfulness': typeof MindfulnessRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/pregnancy': typeof PregnancyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/screens': typeof ScreensRoute
  '/search': typeof SearchRoute
  '/supplements': typeof SupplementsRoute
  '/system': typeof SystemRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/checkin/sleep': typeof CheckinSleepRoute
  '/checkin/steps': typeof CheckinStepsRoute
  '/checkin/water': typeof CheckinWaterRoute
  '/coaches/$id': typeof CoachesIdRouteWithChildren
  '/community/$id': typeof CommunityIdRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/invite': typeof CommunityInviteRoute
  '/cycle/log': typeof CycleLogRoute
  '/journey/awards': typeof JourneyAwardsRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/insights': typeof JourneyInsightsRoute
  '/journey/measurements': typeof JourneyMeasurementsRoute
  '/journey/mood': typeof JourneyMoodRoute
  '/journey/symptoms': typeof JourneySymptomsRoute
  '/mindfulness/$id': typeof MindfulnessIdRoute
  '/nutrition/$id': typeof NutritionIdRoute
  '/nutrition/log': typeof NutritionLogRoute
  '/nutrition/recipes': typeof NutritionRecipesRoute
  '/onboarding/activity': typeof OnboardingActivityRoute
  '/onboarding/auth': typeof OnboardingAuthRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/cycle-data': typeof OnboardingCycleDataRoute
  '/onboarding/diet': typeof OnboardingDietRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/frequency': typeof OnboardingFrequencyRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/level': typeof OnboardingLevelRoute
  '/onboarding/location-pref': typeof OnboardingLocationPrefRoute
  '/onboarding/nutrition-goal': typeof OnboardingNutritionGoalRoute
  '/onboarding/permissions': typeof OnboardingPermissionsRoute
  '/onboarding/stats': typeof OnboardingStatsRoute
  '/onboarding/trial': typeof OnboardingTrialRoute
  '/onboarding/types': typeof OnboardingTypesRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/notifications-prefs': typeof ProfileNotificationsPrefsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/subscription': typeof ProfileSubscriptionRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/live': typeof WorkoutsLiveRoute
  '/workouts/programs': typeof WorkoutsProgramsRoute
  '/workouts/summary': typeof WorkoutsSummaryRoute
  '/coaches/$id/chat': typeof CoachesIdChatRoute
  '/workouts/$id/play': typeof WorkoutsIdPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/404': typeof R404Route
  '/articles': typeof ArticlesRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/challenges': typeof ChallengesRouteWithChildren
  '/checkin': typeof CheckinRouteWithChildren
  '/coaches': typeof CoachesRouteWithChildren
  '/community': typeof CommunityRouteWithChildren
  '/cycle': typeof CycleRouteWithChildren
  '/home': typeof HomeRoute
  '/journey': typeof JourneyRouteWithChildren
  '/mindfulness': typeof MindfulnessRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRouteWithChildren
  '/paywall': typeof PaywallRoute
  '/pregnancy': typeof PregnancyRoute
  '/profile': typeof ProfileRouteWithChildren
  '/screens': typeof ScreensRoute
  '/search': typeof SearchRoute
  '/supplements': typeof SupplementsRoute
  '/system': typeof SystemRoute
  '/workouts': typeof WorkoutsRouteWithChildren
  '/articles/$id': typeof ArticlesIdRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/new-password': typeof AuthNewPasswordRoute
  '/auth/otp': typeof AuthOtpRoute
  '/challenges/$id': typeof ChallengesIdRoute
  '/checkin/sleep': typeof CheckinSleepRoute
  '/checkin/steps': typeof CheckinStepsRoute
  '/checkin/water': typeof CheckinWaterRoute
  '/coaches/$id': typeof CoachesIdRouteWithChildren
  '/community/$id': typeof CommunityIdRoute
  '/community/groups': typeof CommunityGroupsRoute
  '/community/invite': typeof CommunityInviteRoute
  '/cycle/log': typeof CycleLogRoute
  '/journey/awards': typeof JourneyAwardsRoute
  '/journey/goals': typeof JourneyGoalsRoute
  '/journey/insights': typeof JourneyInsightsRoute
  '/journey/measurements': typeof JourneyMeasurementsRoute
  '/journey/mood': typeof JourneyMoodRoute
  '/journey/symptoms': typeof JourneySymptomsRoute
  '/mindfulness/$id': typeof MindfulnessIdRoute
  '/nutrition/$id': typeof NutritionIdRoute
  '/nutrition/log': typeof NutritionLogRoute
  '/nutrition/recipes': typeof NutritionRecipesRoute
  '/onboarding/activity': typeof OnboardingActivityRoute
  '/onboarding/auth': typeof OnboardingAuthRoute
  '/onboarding/complete': typeof OnboardingCompleteRoute
  '/onboarding/cycle-data': typeof OnboardingCycleDataRoute
  '/onboarding/diet': typeof OnboardingDietRoute
  '/onboarding/dob': typeof OnboardingDobRoute
  '/onboarding/frequency': typeof OnboardingFrequencyRoute
  '/onboarding/goal': typeof OnboardingGoalRoute
  '/onboarding/level': typeof OnboardingLevelRoute
  '/onboarding/location-pref': typeof OnboardingLocationPrefRoute
  '/onboarding/nutrition-goal': typeof OnboardingNutritionGoalRoute
  '/onboarding/permissions': typeof OnboardingPermissionsRoute
  '/onboarding/stats': typeof OnboardingStatsRoute
  '/onboarding/trial': typeof OnboardingTrialRoute
  '/onboarding/types': typeof OnboardingTypesRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/profile/edit': typeof ProfileEditRoute
  '/profile/help': typeof ProfileHelpRoute
  '/profile/notifications-prefs': typeof ProfileNotificationsPrefsRoute
  '/profile/payment': typeof ProfilePaymentRoute
  '/profile/privacy': typeof ProfilePrivacyRoute
  '/profile/settings': typeof ProfileSettingsRoute
  '/profile/subscription': typeof ProfileSubscriptionRoute
  '/workouts/$id': typeof WorkoutsIdRouteWithChildren
  '/workouts/live': typeof WorkoutsLiveRoute
  '/workouts/programs': typeof WorkoutsProgramsRoute
  '/workouts/summary': typeof WorkoutsSummaryRoute
  '/coaches/$id/chat': typeof CoachesIdChatRoute
  '/workouts/$id/play': typeof WorkoutsIdPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/404'
    | '/articles'
    | '/assistant'
    | '/challenges'
    | '/checkin'
    | '/coaches'
    | '/community'
    | '/cycle'
    | '/home'
    | '/journey'
    | '/mindfulness'
    | '/notifications'
    | '/nutrition'
    | '/paywall'
    | '/pregnancy'
    | '/profile'
    | '/screens'
    | '/search'
    | '/supplements'
    | '/system'
    | '/workouts'
    | '/articles/$id'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/challenges/$id'
    | '/checkin/sleep'
    | '/checkin/steps'
    | '/checkin/water'
    | '/coaches/$id'
    | '/community/$id'
    | '/community/groups'
    | '/community/invite'
    | '/cycle/log'
    | '/journey/awards'
    | '/journey/goals'
    | '/journey/insights'
    | '/journey/measurements'
    | '/journey/mood'
    | '/journey/symptoms'
    | '/mindfulness/$id'
    | '/nutrition/$id'
    | '/nutrition/log'
    | '/nutrition/recipes'
    | '/onboarding/activity'
    | '/onboarding/auth'
    | '/onboarding/complete'
    | '/onboarding/cycle-data'
    | '/onboarding/diet'
    | '/onboarding/dob'
    | '/onboarding/frequency'
    | '/onboarding/goal'
    | '/onboarding/level'
    | '/onboarding/location-pref'
    | '/onboarding/nutrition-goal'
    | '/onboarding/permissions'
    | '/onboarding/stats'
    | '/onboarding/trial'
    | '/onboarding/types'
    | '/onboarding/welcome'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/notifications-prefs'
    | '/profile/payment'
    | '/profile/privacy'
    | '/profile/settings'
    | '/profile/subscription'
    | '/workouts/$id'
    | '/workouts/live'
    | '/workouts/programs'
    | '/workouts/summary'
    | '/coaches/$id/chat'
    | '/workouts/$id/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/404'
    | '/articles'
    | '/assistant'
    | '/challenges'
    | '/checkin'
    | '/coaches'
    | '/community'
    | '/cycle'
    | '/home'
    | '/journey'
    | '/mindfulness'
    | '/notifications'
    | '/nutrition'
    | '/paywall'
    | '/pregnancy'
    | '/profile'
    | '/screens'
    | '/search'
    | '/supplements'
    | '/system'
    | '/workouts'
    | '/articles/$id'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/challenges/$id'
    | '/checkin/sleep'
    | '/checkin/steps'
    | '/checkin/water'
    | '/coaches/$id'
    | '/community/$id'
    | '/community/groups'
    | '/community/invite'
    | '/cycle/log'
    | '/journey/awards'
    | '/journey/goals'
    | '/journey/insights'
    | '/journey/measurements'
    | '/journey/mood'
    | '/journey/symptoms'
    | '/mindfulness/$id'
    | '/nutrition/$id'
    | '/nutrition/log'
    | '/nutrition/recipes'
    | '/onboarding/activity'
    | '/onboarding/auth'
    | '/onboarding/complete'
    | '/onboarding/cycle-data'
    | '/onboarding/diet'
    | '/onboarding/dob'
    | '/onboarding/frequency'
    | '/onboarding/goal'
    | '/onboarding/level'
    | '/onboarding/location-pref'
    | '/onboarding/nutrition-goal'
    | '/onboarding/permissions'
    | '/onboarding/stats'
    | '/onboarding/trial'
    | '/onboarding/types'
    | '/onboarding/welcome'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/notifications-prefs'
    | '/profile/payment'
    | '/profile/privacy'
    | '/profile/settings'
    | '/profile/subscription'
    | '/workouts/$id'
    | '/workouts/live'
    | '/workouts/programs'
    | '/workouts/summary'
    | '/coaches/$id/chat'
    | '/workouts/$id/play'
  id:
    | '__root__'
    | '/'
    | '/404'
    | '/articles'
    | '/assistant'
    | '/challenges'
    | '/checkin'
    | '/coaches'
    | '/community'
    | '/cycle'
    | '/home'
    | '/journey'
    | '/mindfulness'
    | '/notifications'
    | '/nutrition'
    | '/paywall'
    | '/pregnancy'
    | '/profile'
    | '/screens'
    | '/search'
    | '/supplements'
    | '/system'
    | '/workouts'
    | '/articles/$id'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/new-password'
    | '/auth/otp'
    | '/challenges/$id'
    | '/checkin/sleep'
    | '/checkin/steps'
    | '/checkin/water'
    | '/coaches/$id'
    | '/community/$id'
    | '/community/groups'
    | '/community/invite'
    | '/cycle/log'
    | '/journey/awards'
    | '/journey/goals'
    | '/journey/insights'
    | '/journey/measurements'
    | '/journey/mood'
    | '/journey/symptoms'
    | '/mindfulness/$id'
    | '/nutrition/$id'
    | '/nutrition/log'
    | '/nutrition/recipes'
    | '/onboarding/activity'
    | '/onboarding/auth'
    | '/onboarding/complete'
    | '/onboarding/cycle-data'
    | '/onboarding/diet'
    | '/onboarding/dob'
    | '/onboarding/frequency'
    | '/onboarding/goal'
    | '/onboarding/level'
    | '/onboarding/location-pref'
    | '/onboarding/nutrition-goal'
    | '/onboarding/permissions'
    | '/onboarding/stats'
    | '/onboarding/trial'
    | '/onboarding/types'
    | '/onboarding/welcome'
    | '/profile/edit'
    | '/profile/help'
    | '/profile/notifications-prefs'
    | '/profile/payment'
    | '/profile/privacy'
    | '/profile/settings'
    | '/profile/subscription'
    | '/workouts/$id'
    | '/workouts/live'
    | '/workouts/programs'
    | '/workouts/summary'
    | '/coaches/$id/chat'
    | '/workouts/$id/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R404Route: typeof R404Route
  ArticlesRoute: typeof ArticlesRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  ChallengesRoute: typeof ChallengesRouteWithChildren
  CheckinRoute: typeof CheckinRouteWithChildren
  CoachesRoute: typeof CoachesRouteWithChildren
  CommunityRoute: typeof CommunityRouteWithChildren
  CycleRoute: typeof CycleRouteWithChildren
  HomeRoute: typeof HomeRoute
  JourneyRoute: typeof JourneyRouteWithChildren
  MindfulnessRoute: typeof MindfulnessRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  NutritionRoute: typeof NutritionRouteWithChildren
  PaywallRoute: typeof PaywallRoute
  PregnancyRoute: typeof PregnancyRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  ScreensRoute: typeof ScreensRoute
  SearchRoute: typeof SearchRoute
  SupplementsRoute: typeof SupplementsRoute
  SystemRoute: typeof SystemRoute
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthNewPasswordRoute: typeof AuthNewPasswordRoute
  AuthOtpRoute: typeof AuthOtpRoute
  OnboardingActivityRoute: typeof OnboardingActivityRoute
  OnboardingAuthRoute: typeof OnboardingAuthRoute
  OnboardingCompleteRoute: typeof OnboardingCompleteRoute
  OnboardingCycleDataRoute: typeof OnboardingCycleDataRoute
  OnboardingDietRoute: typeof OnboardingDietRoute
  OnboardingDobRoute: typeof OnboardingDobRoute
  OnboardingFrequencyRoute: typeof OnboardingFrequencyRoute
  OnboardingGoalRoute: typeof OnboardingGoalRoute
  OnboardingLevelRoute: typeof OnboardingLevelRoute
  OnboardingLocationPrefRoute: typeof OnboardingLocationPrefRoute
  OnboardingNutritionGoalRoute: typeof OnboardingNutritionGoalRoute
  OnboardingPermissionsRoute: typeof OnboardingPermissionsRoute
  OnboardingStatsRoute: typeof OnboardingStatsRoute
  OnboardingTrialRoute: typeof OnboardingTrialRoute
  OnboardingTypesRoute: typeof OnboardingTypesRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplements': {
      id: '/supplements'
      path: '/supplements'
      fullPath: '/supplements'
      preLoaderRoute: typeof SupplementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pregnancy': {
      id: '/pregnancy'
      path: '/pregnancy'
      fullPath: '/pregnancy'
      preLoaderRoute: typeof PregnancyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paywall': {
      id: '/paywall'
      path: '/paywall'
      fullPath: '/paywall'
      preLoaderRoute: typeof PaywallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mindfulness': {
      id: '/mindfulness'
      path: '/mindfulness'
      fullPath: '/mindfulness'
      preLoaderRoute: typeof MindfulnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cycle': {
      id: '/cycle'
      path: '/cycle'
      fullPath: '/cycle'
      preLoaderRoute: typeof CycleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenges': {
      id: '/challenges'
      path: '/challenges'
      fullPath: '/challenges'
      preLoaderRoute: typeof ChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles': {
      id: '/articles'
      path: '/articles'
      fullPath: '/articles'
      preLoaderRoute: typeof ArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/404': {
      id: '/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof R404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/summary': {
      id: '/workouts/summary'
      path: '/summary'
      fullPath: '/workouts/summary'
      preLoaderRoute: typeof WorkoutsSummaryRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/programs': {
      id: '/workouts/programs'
      path: '/programs'
      fullPath: '/workouts/programs'
      preLoaderRoute: typeof WorkoutsProgramsRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/live': {
      id: '/workouts/live'
      path: '/live'
      fullPath: '/workouts/live'
      preLoaderRoute: typeof WorkoutsLiveRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$id': {
      id: '/workouts/$id'
      path: '/$id'
      fullPath: '/workouts/$id'
      preLoaderRoute: typeof WorkoutsIdRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/profile/subscription': {
      id: '/profile/subscription'
      path: '/subscription'
      fullPath: '/profile/subscription'
      preLoaderRoute: typeof ProfileSubscriptionRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/settings': {
      id: '/profile/settings'
      path: '/settings'
      fullPath: '/profile/settings'
      preLoaderRoute: typeof ProfileSettingsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/privacy': {
      id: '/profile/privacy'
      path: '/privacy'
      fullPath: '/profile/privacy'
      preLoaderRoute: typeof ProfilePrivacyRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/payment': {
      id: '/profile/payment'
      path: '/payment'
      fullPath: '/profile/payment'
      preLoaderRoute: typeof ProfilePaymentRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/notifications-prefs': {
      id: '/profile/notifications-prefs'
      path: '/notifications-prefs'
      fullPath: '/profile/notifications-prefs'
      preLoaderRoute: typeof ProfileNotificationsPrefsRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/help': {
      id: '/profile/help'
      path: '/help'
      fullPath: '/profile/help'
      preLoaderRoute: typeof ProfileHelpRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/onboarding/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/types': {
      id: '/onboarding/types'
      path: '/onboarding/types'
      fullPath: '/onboarding/types'
      preLoaderRoute: typeof OnboardingTypesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/trial': {
      id: '/onboarding/trial'
      path: '/onboarding/trial'
      fullPath: '/onboarding/trial'
      preLoaderRoute: typeof OnboardingTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/stats': {
      id: '/onboarding/stats'
      path: '/onboarding/stats'
      fullPath: '/onboarding/stats'
      preLoaderRoute: typeof OnboardingStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/permissions': {
      id: '/onboarding/permissions'
      path: '/onboarding/permissions'
      fullPath: '/onboarding/permissions'
      preLoaderRoute: typeof OnboardingPermissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/nutrition-goal': {
      id: '/onboarding/nutrition-goal'
      path: '/onboarding/nutrition-goal'
      fullPath: '/onboarding/nutrition-goal'
      preLoaderRoute: typeof OnboardingNutritionGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/location-pref': {
      id: '/onboarding/location-pref'
      path: '/onboarding/location-pref'
      fullPath: '/onboarding/location-pref'
      preLoaderRoute: typeof OnboardingLocationPrefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/level': {
      id: '/onboarding/level'
      path: '/onboarding/level'
      fullPath: '/onboarding/level'
      preLoaderRoute: typeof OnboardingLevelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/goal': {
      id: '/onboarding/goal'
      path: '/onboarding/goal'
      fullPath: '/onboarding/goal'
      preLoaderRoute: typeof OnboardingGoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/frequency': {
      id: '/onboarding/frequency'
      path: '/onboarding/frequency'
      fullPath: '/onboarding/frequency'
      preLoaderRoute: typeof OnboardingFrequencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/dob': {
      id: '/onboarding/dob'
      path: '/onboarding/dob'
      fullPath: '/onboarding/dob'
      preLoaderRoute: typeof OnboardingDobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/diet': {
      id: '/onboarding/diet'
      path: '/onboarding/diet'
      fullPath: '/onboarding/diet'
      preLoaderRoute: typeof OnboardingDietRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/cycle-data': {
      id: '/onboarding/cycle-data'
      path: '/onboarding/cycle-data'
      fullPath: '/onboarding/cycle-data'
      preLoaderRoute: typeof OnboardingCycleDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/complete': {
      id: '/onboarding/complete'
      path: '/onboarding/complete'
      fullPath: '/onboarding/complete'
      preLoaderRoute: typeof OnboardingCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/auth': {
      id: '/onboarding/auth'
      path: '/onboarding/auth'
      fullPath: '/onboarding/auth'
      preLoaderRoute: typeof OnboardingAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/activity': {
      id: '/onboarding/activity'
      path: '/onboarding/activity'
      fullPath: '/onboarding/activity'
      preLoaderRoute: typeof OnboardingActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition/recipes': {
      id: '/nutrition/recipes'
      path: '/recipes'
      fullPath: '/nutrition/recipes'
      preLoaderRoute: typeof NutritionRecipesRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/log': {
      id: '/nutrition/log'
      path: '/log'
      fullPath: '/nutrition/log'
      preLoaderRoute: typeof NutritionLogRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/nutrition/$id': {
      id: '/nutrition/$id'
      path: '/$id'
      fullPath: '/nutrition/$id'
      preLoaderRoute: typeof NutritionIdRouteImport
      parentRoute: typeof NutritionRoute
    }
    '/mindfulness/$id': {
      id: '/mindfulness/$id'
      path: '/$id'
      fullPath: '/mindfulness/$id'
      preLoaderRoute: typeof MindfulnessIdRouteImport
      parentRoute: typeof MindfulnessRoute
    }
    '/journey/symptoms': {
      id: '/journey/symptoms'
      path: '/symptoms'
      fullPath: '/journey/symptoms'
      preLoaderRoute: typeof JourneySymptomsRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/mood': {
      id: '/journey/mood'
      path: '/mood'
      fullPath: '/journey/mood'
      preLoaderRoute: typeof JourneyMoodRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/measurements': {
      id: '/journey/measurements'
      path: '/measurements'
      fullPath: '/journey/measurements'
      preLoaderRoute: typeof JourneyMeasurementsRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/insights': {
      id: '/journey/insights'
      path: '/insights'
      fullPath: '/journey/insights'
      preLoaderRoute: typeof JourneyInsightsRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/goals': {
      id: '/journey/goals'
      path: '/goals'
      fullPath: '/journey/goals'
      preLoaderRoute: typeof JourneyGoalsRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/journey/awards': {
      id: '/journey/awards'
      path: '/awards'
      fullPath: '/journey/awards'
      preLoaderRoute: typeof JourneyAwardsRouteImport
      parentRoute: typeof JourneyRoute
    }
    '/cycle/log': {
      id: '/cycle/log'
      path: '/log'
      fullPath: '/cycle/log'
      preLoaderRoute: typeof CycleLogRouteImport
      parentRoute: typeof CycleRoute
    }
    '/community/invite': {
      id: '/community/invite'
      path: '/invite'
      fullPath: '/community/invite'
      preLoaderRoute: typeof CommunityInviteRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/groups': {
      id: '/community/groups'
      path: '/groups'
      fullPath: '/community/groups'
      preLoaderRoute: typeof CommunityGroupsRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/community/$id': {
      id: '/community/$id'
      path: '/$id'
      fullPath: '/community/$id'
      preLoaderRoute: typeof CommunityIdRouteImport
      parentRoute: typeof CommunityRoute
    }
    '/coaches/$id': {
      id: '/coaches/$id'
      path: '/$id'
      fullPath: '/coaches/$id'
      preLoaderRoute: typeof CoachesIdRouteImport
      parentRoute: typeof CoachesRoute
    }
    '/checkin/water': {
      id: '/checkin/water'
      path: '/water'
      fullPath: '/checkin/water'
      preLoaderRoute: typeof CheckinWaterRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/steps': {
      id: '/checkin/steps'
      path: '/steps'
      fullPath: '/checkin/steps'
      preLoaderRoute: typeof CheckinStepsRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/sleep': {
      id: '/checkin/sleep'
      path: '/sleep'
      fullPath: '/checkin/sleep'
      preLoaderRoute: typeof CheckinSleepRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/challenges/$id': {
      id: '/challenges/$id'
      path: '/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof ChallengesIdRouteImport
      parentRoute: typeof ChallengesRoute
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/new-password': {
      id: '/auth/new-password'
      path: '/auth/new-password'
      fullPath: '/auth/new-password'
      preLoaderRoute: typeof AuthNewPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articles/$id': {
      id: '/articles/$id'
      path: '/$id'
      fullPath: '/articles/$id'
      preLoaderRoute: typeof ArticlesIdRouteImport
      parentRoute: typeof ArticlesRoute
    }
    '/workouts/$id/play': {
      id: '/workouts/$id/play'
      path: '/play'
      fullPath: '/workouts/$id/play'
      preLoaderRoute: typeof WorkoutsIdPlayRouteImport
      parentRoute: typeof WorkoutsIdRoute
    }
    '/coaches/$id/chat': {
      id: '/coaches/$id/chat'
      path: '/chat'
      fullPath: '/coaches/$id/chat'
      preLoaderRoute: typeof CoachesIdChatRouteImport
      parentRoute: typeof CoachesIdRoute
    }
  }
}

interface ArticlesRouteChildren {
  ArticlesIdRoute: typeof ArticlesIdRoute
}

const ArticlesRouteChildren: ArticlesRouteChildren = {
  ArticlesIdRoute: ArticlesIdRoute,
}

const ArticlesRouteWithChildren = ArticlesRoute._addFileChildren(
  ArticlesRouteChildren,
)

interface ChallengesRouteChildren {
  ChallengesIdRoute: typeof ChallengesIdRoute
}

const ChallengesRouteChildren: ChallengesRouteChildren = {
  ChallengesIdRoute: ChallengesIdRoute,
}

const ChallengesRouteWithChildren = ChallengesRoute._addFileChildren(
  ChallengesRouteChildren,
)

interface CheckinRouteChildren {
  CheckinSleepRoute: typeof CheckinSleepRoute
  CheckinStepsRoute: typeof CheckinStepsRoute
  CheckinWaterRoute: typeof CheckinWaterRoute
}

const CheckinRouteChildren: CheckinRouteChildren = {
  CheckinSleepRoute: CheckinSleepRoute,
  CheckinStepsRoute: CheckinStepsRoute,
  CheckinWaterRoute: CheckinWaterRoute,
}

const CheckinRouteWithChildren =
  CheckinRoute._addFileChildren(CheckinRouteChildren)

interface CoachesIdRouteChildren {
  CoachesIdChatRoute: typeof CoachesIdChatRoute
}

const CoachesIdRouteChildren: CoachesIdRouteChildren = {
  CoachesIdChatRoute: CoachesIdChatRoute,
}

const CoachesIdRouteWithChildren = CoachesIdRoute._addFileChildren(
  CoachesIdRouteChildren,
)

interface CoachesRouteChildren {
  CoachesIdRoute: typeof CoachesIdRouteWithChildren
}

const CoachesRouteChildren: CoachesRouteChildren = {
  CoachesIdRoute: CoachesIdRouteWithChildren,
}

const CoachesRouteWithChildren =
  CoachesRoute._addFileChildren(CoachesRouteChildren)

interface CommunityRouteChildren {
  CommunityIdRoute: typeof CommunityIdRoute
  CommunityGroupsRoute: typeof CommunityGroupsRoute
  CommunityInviteRoute: typeof CommunityInviteRoute
}

const CommunityRouteChildren: CommunityRouteChildren = {
  CommunityIdRoute: CommunityIdRoute,
  CommunityGroupsRoute: CommunityGroupsRoute,
  CommunityInviteRoute: CommunityInviteRoute,
}

const CommunityRouteWithChildren = CommunityRoute._addFileChildren(
  CommunityRouteChildren,
)

interface CycleRouteChildren {
  CycleLogRoute: typeof CycleLogRoute
}

const CycleRouteChildren: CycleRouteChildren = {
  CycleLogRoute: CycleLogRoute,
}

const CycleRouteWithChildren = CycleRoute._addFileChildren(CycleRouteChildren)

interface JourneyRouteChildren {
  JourneyAwardsRoute: typeof JourneyAwardsRoute
  JourneyGoalsRoute: typeof JourneyGoalsRoute
  JourneyInsightsRoute: typeof JourneyInsightsRoute
  JourneyMeasurementsRoute: typeof JourneyMeasurementsRoute
  JourneyMoodRoute: typeof JourneyMoodRoute
  JourneySymptomsRoute: typeof JourneySymptomsRoute
}

const JourneyRouteChildren: JourneyRouteChildren = {
  JourneyAwardsRoute: JourneyAwardsRoute,
  JourneyGoalsRoute: JourneyGoalsRoute,
  JourneyInsightsRoute: JourneyInsightsRoute,
  JourneyMeasurementsRoute: JourneyMeasurementsRoute,
  JourneyMoodRoute: JourneyMoodRoute,
  JourneySymptomsRoute: JourneySymptomsRoute,
}

const JourneyRouteWithChildren =
  JourneyRoute._addFileChildren(JourneyRouteChildren)

interface MindfulnessRouteChildren {
  MindfulnessIdRoute: typeof MindfulnessIdRoute
}

const MindfulnessRouteChildren: MindfulnessRouteChildren = {
  MindfulnessIdRoute: MindfulnessIdRoute,
}

const MindfulnessRouteWithChildren = MindfulnessRoute._addFileChildren(
  MindfulnessRouteChildren,
)

interface NutritionRouteChildren {
  NutritionIdRoute: typeof NutritionIdRoute
  NutritionLogRoute: typeof NutritionLogRoute
  NutritionRecipesRoute: typeof NutritionRecipesRoute
}

const NutritionRouteChildren: NutritionRouteChildren = {
  NutritionIdRoute: NutritionIdRoute,
  NutritionLogRoute: NutritionLogRoute,
  NutritionRecipesRoute: NutritionRecipesRoute,
}

const NutritionRouteWithChildren = NutritionRoute._addFileChildren(
  NutritionRouteChildren,
)

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
  ProfileHelpRoute: typeof ProfileHelpRoute
  ProfileNotificationsPrefsRoute: typeof ProfileNotificationsPrefsRoute
  ProfilePaymentRoute: typeof ProfilePaymentRoute
  ProfilePrivacyRoute: typeof ProfilePrivacyRoute
  ProfileSettingsRoute: typeof ProfileSettingsRoute
  ProfileSubscriptionRoute: typeof ProfileSubscriptionRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
  ProfileHelpRoute: ProfileHelpRoute,
  ProfileNotificationsPrefsRoute: ProfileNotificationsPrefsRoute,
  ProfilePaymentRoute: ProfilePaymentRoute,
  ProfilePrivacyRoute: ProfilePrivacyRoute,
  ProfileSettingsRoute: ProfileSettingsRoute,
  ProfileSubscriptionRoute: ProfileSubscriptionRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

interface WorkoutsIdRouteChildren {
  WorkoutsIdPlayRoute: typeof WorkoutsIdPlayRoute
}

const WorkoutsIdRouteChildren: WorkoutsIdRouteChildren = {
  WorkoutsIdPlayRoute: WorkoutsIdPlayRoute,
}

const WorkoutsIdRouteWithChildren = WorkoutsIdRoute._addFileChildren(
  WorkoutsIdRouteChildren,
)

interface WorkoutsRouteChildren {
  WorkoutsIdRoute: typeof WorkoutsIdRouteWithChildren
  WorkoutsLiveRoute: typeof WorkoutsLiveRoute
  WorkoutsProgramsRoute: typeof WorkoutsProgramsRoute
  WorkoutsSummaryRoute: typeof WorkoutsSummaryRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsIdRoute: WorkoutsIdRouteWithChildren,
  WorkoutsLiveRoute: WorkoutsLiveRoute,
  WorkoutsProgramsRoute: WorkoutsProgramsRoute,
  WorkoutsSummaryRoute: WorkoutsSummaryRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R404Route: R404Route,
  ArticlesRoute: ArticlesRouteWithChildren,
  AssistantRoute: AssistantRoute,
  ChallengesRoute: ChallengesRouteWithChildren,
  CheckinRoute: CheckinRouteWithChildren,
  CoachesRoute: CoachesRouteWithChildren,
  CommunityRoute: CommunityRouteWithChildren,
  CycleRoute: CycleRouteWithChildren,
  HomeRoute: HomeRoute,
  JourneyRoute: JourneyRouteWithChildren,
  MindfulnessRoute: MindfulnessRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  NutritionRoute: NutritionRouteWithChildren,
  PaywallRoute: PaywallRoute,
  PregnancyRoute: PregnancyRoute,
  ProfileRoute: ProfileRouteWithChildren,
  ScreensRoute: ScreensRoute,
  SearchRoute: SearchRoute,
  SupplementsRoute: SupplementsRoute,
  SystemRoute: SystemRoute,
  WorkoutsRoute: WorkoutsRouteWithChildren,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthNewPasswordRoute: AuthNewPasswordRoute,
  AuthOtpRoute: AuthOtpRoute,
  OnboardingActivityRoute: OnboardingActivityRoute,
  OnboardingAuthRoute: OnboardingAuthRoute,
  OnboardingCompleteRoute: OnboardingCompleteRoute,
  OnboardingCycleDataRoute: OnboardingCycleDataRoute,
  OnboardingDietRoute: OnboardingDietRoute,
  OnboardingDobRoute: OnboardingDobRoute,
  OnboardingFrequencyRoute: OnboardingFrequencyRoute,
  OnboardingGoalRoute: OnboardingGoalRoute,
  OnboardingLevelRoute: OnboardingLevelRoute,
  OnboardingLocationPrefRoute: OnboardingLocationPrefRoute,
  OnboardingNutritionGoalRoute: OnboardingNutritionGoalRoute,
  OnboardingPermissionsRoute: OnboardingPermissionsRoute,
  OnboardingStatsRoute: OnboardingStatsRoute,
  OnboardingTrialRoute: OnboardingTrialRoute,
  OnboardingTypesRoute: OnboardingTypesRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
